/**
 * ClickHouse async batch writer for usage logs (official @clickhouse/client SDK).
 *
 * Positioning: **Self-hosted / Cloud ClickHouse usage reporting**, used to show token consumption per user (by turn).
 * Independent of Langfuse / Opik reporting — Langfuse handles trace visualization, while ClickHouse acts as usage/billing data source.
 *
 * Features:
 * - Official SDK (createClient + insert(JSONEachRow) + command(DDL))
 * - In-memory buffer + periodic/threshold flush
 * - Retry queue on failure (with buffer cap to prevent OOM)
 * - Error-silent: never blocks or degrades business requests
 * - Graceful shutdown: flushes remaining buffer before exit
 *
 * Reliability note: Failed rows are requeued and retried, but when buffer exceeds cap, oldest rows are dropped ("best-effort" rather than
 * "zero-loss"). If billing requires zero-loss, persistent WAL must be added in future — not implemented currently.
 */

import type { ClickHouseClient } from "@clickhouse/client";
import { log } from "./report/log.js";
import { hostname } from "node:os";
import { createHash } from "node:crypto";
import { computeCreditDelta } from "./credit-reporter.js";
import { getModelPricing, resolveModelName } from "./pricing.js";
import type { CreditPricingConfig, CreditPricingEntry } from "./types.js";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ClickHouseConfig {
  /** Whether ClickHouse logging is enabled. */
  enabled: boolean;
  /** ClickHouse HTTP endpoint (e.g. http://<CLICKHOUSE_HOST>:8123). */
  url: string;
  /** Database name. */
  database: string;
  /** Table name for usage logs. */
  table: string;
  /** Raw usage traceability table (non-TokenHub / unrecognized format). */
  rawTable: string;
  /** Auth user. */
  user: string;
  /** Auth password. */
  password: string;
  /** Flush interval in ms (default: 5000). */
  flushIntervalMs: number;
  /** Buffer flush threshold in rows (default: 50). */
  flushThreshold: number;
  /** Data retention TTL in days. 0 = no TTL. Default: 0. */
  ttlDays: number;
}

/** One row = one upstream request (primary usage or extension telemetry). turn is identified by (session_key, turn_seq). */
export interface ClickHouseRow {
  timestamp: string;       // ClickHouse DateTime64 format "YYYY-MM-DD HH:MM:SS.mmm"
  event: string;           // 'usage' | 'analyzer_usage' (extension telemetry)
  session_key: string;     // Session isolation key (for turn aggregation)
  turn_seq: number;        // Turn sequence number
  user_input: string;      // User input of this turn (non-empty for first request after denoising; empty for rest)
  model_id: string;
  model_name: string;      // UI display name (from pricing table modelName; fallback to modelId on miss)
  user_id: string;         // User identifier (user_id when auth enabled, else SHA-256(apiKey)[:8])
  upstream_url: string;
  stream: number;          // 0 or 1
  prompt_tokens: number;
  completion_tokens: number;
  total_tokens: number;
  cache_hit_tokens: number;    // Hit (cache_read)
  cache_miss_tokens: number;
  cache_write_tokens: number;  // Write cache (cache_creation, total)
  // ── TokenHub Anthropic raw fields (unconverted) ─────────────────────────
  input_tokens: number;                                  // Non-cached input (TokenHub excludes cache)
  cache_creation_ephemeral_5m_input_tokens: number;      // 5m TTL cache write
  cache_creation_ephemeral_1h_input_tokens: number;      // 1h TTL cache write
  credit: number;
  credit_saved: number;        // Credit saved by routing (has value only when event=usage and routed_from is non-empty)
  routed_from: string;
  space_id: string;            // Space / tenant identifier (extracted from /proxy/<spaceId>/... path)
  source_tag: string;          // Source tag, constant "proxy"
  host: string;
  upstream_request_id: string; // Upstream response header `x-request-id` (generated by tokenhub/OpenAI compatible gateway), for cross-system tracing
  /**
   * Compression tokens saved: max(0, pre_compress_tokens − post_compress_tokens).
   * From cost-guard extensionStats; 0 when uncompressed.
   */
  compress_tokens_saved: number;
  /**
   * Pre-compression token count reported by compression service (counts only content where numbers were returned).
   *
   * Specification note: Calculated by compression service's own tokenizer, not using the same ruler as `input_tokens`
   * in the same row (upstream model's billing specification). They cannot be subtracted or converted into cost directly.
   * Its purpose is computing compression ratio `post / pre`.
   */
  pre_compress_tokens: number;
  /** Post-compression token count of the same batch; items retaining original text are counted same as pre-compression. */
  post_compress_tokens: number;
}

/**
 * Raw usage row for traceability (non-TokenHub or unrecognized format).
 *
 * Fields aligned with main table `ClickHouseRow` as much as possible for cross-table JOIN queries.
 * Differences from `usage_logs`:
 *  - Preserves raw `usage` (JSON string) without parsing
 *  - `reason` field records cause of falling into raw table (unknown_model / invalid_format / ...)
 *  - `key_id` and `user_id` **double-written** (legacy table uses key_id, new table uses user_id),
 *    achieving bidirectional compatibility via ClickHouse `JSONEachRow` fault tolerance
 */
export interface ClickHouseRawUsageRow {
  timestamp: string;
  model_id: string;
  model_name: string;          // Display name (aligned with main table; fallback to model_id when no pricing config)
  key_id: string;              // Legacy column (backwards compatibility)
  user_id: string;             // New column (aligned with main table user_id), value = key_id
  session_key: string;
  turn_seq: number;            // Aligned with main table
  user_input: string;          // Aligned with main table (user input prefix)
  upstream_url: string;
  stream: number;
  usage: string;               // JSON.stringify(raw usage), unmodified
  reason: string;              // 'non_tokenhub' | 'unknown_model' | 'invalid_format' | 'invalid_credit' | 'report_failed'
  routed_from: string;         // Original model before routing
  space_id: string;            // Space/tenant identifier (extracted from /proxy/<spaceId>/...)
  source_tag: string;          // Source tag, constant "proxy"
  host: string;
  upstream_request_id: string; // Upstream response header `x-request-id` (for tracing; aligned with main table)
}

// ── Writer state ────────────────────────────────────────────────────────────

const HOST_ID = hostname();

let config: ClickHouseConfig | null = null;
let client: ClickHouseClient | null = null;
let buffer: ClickHouseRow[] = [];
let rawBuffer: ClickHouseRawUsageRow[] = [];
let flushTimer: ReturnType<typeof setInterval> | null = null;
let disabled = false;

/**
 * Initialize the ClickHouse writer.
 * Must be called once at startup. Idempotent.
 */
export function initClickHouse(cfg: ClickHouseConfig): void {
  if (!cfg.enabled) {
    disabled = true;
    return;
  }
  if (!cfg.url) {
    log.warn("clickhouse.init.skipped", { reason: "empty url" });
    disabled = true;
    return;
  }

  config = cfg;
  disabled = false;

  // Periodic flush (both main and raw buffers)
  flushTimer = setInterval(() => {
    void flush();
    void flushRaw();
    // Internal telemetry buffers (§7.1) — silent fallback against unhandledRejection
    void flushSessionInit().catch(() => {});
    void flushToolCall().catch(() => {});
  }, cfg.flushIntervalMs);
  flushTimer.unref(); // Don't prevent process exit

  log.info("clickhouse.init", {
    url: cfg.url,
    database: cfg.database,
    table: cfg.table,
    flushIntervalMs: cfg.flushIntervalMs,
    flushThreshold: cfg.flushThreshold,
    ttlDays: cfg.ttlDays,
  });

  // Fire-and-forget: create client + database + table (idempotent)
  ensureClickHouse(cfg).catch((err: unknown) => {
    log.warn("clickhouse.init.ensureFailed", {
      error: err instanceof Error ? err.message : String(err),
    });
  });
}

/**
 * Create the SDK client (against the `default` db for DDL), ensure database +
 * table exist, then re-point the client at the target database for inserts.
 */
async function ensureClickHouse(cfg: ClickHouseConfig): Promise<void> {
  const { createClient } = await import("@clickhouse/client");

  // Bootstrap client (no database bound) to create the target database.
  const bootstrap = createClient({
    url: cfg.url,
    username: cfg.user,
    password: cfg.password,
    request_timeout: 10_000,
  });

  try {
    await bootstrap.command({
      query: `CREATE DATABASE IF NOT EXISTS ${cfg.database}`,
      clickhouse_settings: { wait_end_of_query: 1 },
    });
  } finally {
    await bootstrap.close().catch(() => {});
  }

  // Target client bound to the database, reused for all inserts.
  client = createClient({
    url: cfg.url,
    username: cfg.user,
    password: cfg.password,
    database: cfg.database,
    request_timeout: 10_000,
    keep_alive: { enabled: true },
  });

  const ttlClause = cfg.ttlDays > 0 ? `TTL timestamp + INTERVAL ${cfg.ttlDays} DAY` : "";
  const ddl = [
    `CREATE TABLE IF NOT EXISTS ${cfg.table} (`,
    "  timestamp DateTime64(3, 'Asia/Shanghai'),",
    "  event LowCardinality(String),",
    "  session_key String,",
    "  turn_seq UInt32,",
    "  user_input String,",
    "  model_id String,",
    "  model_name String DEFAULT '',",
    "  user_id String,",
    "  upstream_url String,",
    "  stream UInt8,",
    "  prompt_tokens UInt64,",
    "  completion_tokens UInt64,",
    "  total_tokens UInt64,",
    "  cache_hit_tokens UInt64,",
    "  cache_miss_tokens UInt64,",
    "  cache_write_tokens UInt64,",
    "  input_tokens UInt64 DEFAULT 0,",
    "  cache_creation_ephemeral_5m_input_tokens UInt64 DEFAULT 0,",
    "  cache_creation_ephemeral_1h_input_tokens UInt64 DEFAULT 0,",
    "  credit Float64,",
    "  credit_saved Float64 DEFAULT 0,",
    "  routed_from LowCardinality(String),",
    "  space_id String DEFAULT '',",
    "  source_tag LowCardinality(String) DEFAULT 'proxy',",
    "  host LowCardinality(String),",
    "  upstream_request_id String DEFAULT '',",
    "  compress_tokens_saved UInt64 DEFAULT 0,",
    "  pre_compress_tokens UInt64 DEFAULT 0,",
    "  post_compress_tokens UInt64 DEFAULT 0",
    ") ENGINE = MergeTree()",
    "ORDER BY (user_id, session_key, timestamp)",
    ttlClause,
  ]
    .filter(Boolean)
    .join("\n");

  await client.command({
    query: ddl,
    clickhouse_settings: { wait_end_of_query: 1 },
  });

  // Raw usage table (traceability for non-TokenHub / unrecognized format).
  if (cfg.rawTable) {
    // New table uses user_id as default order key (aligned with main table); legacy table continues key_id (migrate fills user_id column)
    const rawDdl = [
      `CREATE TABLE IF NOT EXISTS ${cfg.rawTable} (`,
      "  timestamp DateTime64(3, 'Asia/Shanghai'),",
      "  model_id String,",
      "  model_name String DEFAULT '',",
      "  key_id LowCardinality(String),",
      "  user_id String DEFAULT '',",
      "  session_key String,",
      "  turn_seq UInt32 DEFAULT 0,",
      "  user_input String DEFAULT '',",
      "  upstream_url String,",
      "  stream UInt8,",
      "  usage String,",
      "  reason LowCardinality(String),",
      "  routed_from String DEFAULT '',",
      "  space_id String DEFAULT '',",
      "  source_tag LowCardinality(String) DEFAULT 'proxy',",
      "  host LowCardinality(String),",
      "  upstream_request_id String DEFAULT ''",
      ") ENGINE = MergeTree()",
      "ORDER BY (user_id, timestamp)",
      ttlClause,
    ]
      .filter(Boolean)
      .join("\n");

    await client.command({
      query: rawDdl,
      clickhouse_settings: { wait_end_of_query: 1 },
    });
  }

  // Fill historical schema drift: execute ALTER TABLE ADD COLUMN IF NOT EXISTS on existing tables.
  // Idempotent; failure does not block (degrades to warn if DDL permission missing, business continues with writable fields).
  await migrateSchema(client, cfg);

  // Internal Usage Telemetry (§7.1) — DDL idempotent registration for two new tables.
  // Startup not blocked on failure: separate try/catch, log warn and continue (same degradation logic as legacy tables).
  try {
    await createTableIfNotExists(client, sessionInitTableDdl());
    await createTableIfNotExists(client, toolCallTableDdl());
    log.info("clickhouse.init.telemetryTableReady", {
      sessionInitTable: `${cfg.database}.${SESSION_INIT_TABLE}`,
      toolCallTable: `${cfg.database}.${TOOL_CALL_TABLE}`,
      ttlDays: TELEMETRY_TTL_DAYS,
    });
  } catch (err: unknown) {
    log.warn("clickhouse.init.telemetryTableFailed", {
      error: err instanceof Error ? err.message : String(err),
    });
  }

  log.info("clickhouse.init.tableReady", {
    table: `${cfg.database}.${cfg.table}`,
    rawTable: cfg.rawTable ? `${cfg.database}.${cfg.rawTable}` : undefined,
    ttlDays: cfg.ttlDays,
  });
}

/**
 * Fill historical schema drift of ClickHouse table schemas.
 *
 * `CREATE TABLE IF NOT EXISTS` executes DDL only when table does not exist. Once table is created,
 * code DDL changes (new columns, type adjustments) will not sync automatically to existing tables.
 * This function iterates over an explicit migration list, executing `ALTER TABLE ADD COLUMN IF NOT EXISTS`
 * for each target table.
 *
 * Features:
 *  - **Idempotent**: `IF NOT EXISTS` is natively guaranteed by ClickHouse (≥20.3), zero cost for repeated runs
 *  - **Failure degradation**: Single column ALTER failure (e.g. app account lacks ALTER permission) → log warn only,
 *    continue processing remaining columns; startup flow not interrupted
 *  - **Change audit**: Finally emits a `clickhouse.migrate.done` summary log
 *
 * This function is called after `CREATE TABLE IF NOT EXISTS` in `initClickHouse`,
 * acting as a no-op for fresh tables (columns defined in CREATE) and filling missing columns for legacy tables.
 *
 * @exported for unit testing.
 */
export async function migrateSchema(
  client: ClickHouseClient,
  cfg: ClickHouseConfig,
): Promise<void> {
  const migrations: Array<{ table: string; column: string; type: string }> = [
    // usage_logs: main table completion (historical gap + added model_name)
    { table: cfg.table, column: "session_key", type: "String" },
    { table: cfg.table, column: "turn_seq", type: "UInt32 DEFAULT 0" },
    { table: cfg.table, column: "user_input", type: "String DEFAULT ''" },
    { table: cfg.table, column: "user_id", type: "String DEFAULT ''" },
    { table: cfg.table, column: "model_name", type: "String DEFAULT ''" },
    { table: cfg.table, column: "input_tokens", type: "UInt64 DEFAULT 0" },
    {
      table: cfg.table,
      column: "cache_creation_ephemeral_5m_input_tokens",
      type: "UInt64 DEFAULT 0",
    },
    {
      table: cfg.table,
      column: "cache_creation_ephemeral_1h_input_tokens",
      type: "UInt64 DEFAULT 0",
    },
    { table: cfg.table, column: "credit_saved", type: "Float64 DEFAULT 0" },
    { table: cfg.table, column: "space_id", type: "String DEFAULT ''" },
    {
      table: cfg.table,
      column: "source_tag",
      type: "LowCardinality(String) DEFAULT 'proxy'",
    },
    // Upstream response header `x-request-id` (returned by OpenAI/Anthropic compatible gateways like tokenhub).
    // Added: for cross-system tracing (client x-request-id → proxy upstream_request_id → upstream logs).
    { table: cfg.table, column: "upstream_request_id", type: "String DEFAULT ''" },
    // cost-guard compression tokens saved: max(0, preCompressTokens − postCompressTokens)
    { table: cfg.table, column: "compress_tokens_saved", type: "UInt64 DEFAULT 0" },
    // Raw counts before and after compression, used to calculate compression ratio — difference alone cannot derive denominator.
    { table: cfg.table, column: "pre_compress_tokens", type: "UInt64 DEFAULT 0" },
    { table: cfg.table, column: "post_compress_tokens", type: "UInt64 DEFAULT 0" },
  ];

  // usage_raw: tracing table completion (added 6 columns + model_name + upstream_request_id)
  if (cfg.rawTable) {
    migrations.push(
      { table: cfg.rawTable, column: "user_id", type: "String DEFAULT ''" },
      { table: cfg.rawTable, column: "model_name", type: "String DEFAULT ''" },
      { table: cfg.rawTable, column: "turn_seq", type: "UInt32 DEFAULT 0" },
      { table: cfg.rawTable, column: "user_input", type: "String DEFAULT ''" },
      { table: cfg.rawTable, column: "routed_from", type: "String DEFAULT ''" },
      { table: cfg.rawTable, column: "space_id", type: "String DEFAULT ''" },
      {
        table: cfg.rawTable,
        column: "source_tag",
        type: "LowCardinality(String) DEFAULT 'proxy'",
      },
      {
        table: cfg.rawTable,
        column: "upstream_request_id",
        type: "String DEFAULT ''",
      },
    );
  }

  // tool_call_logs: add reject_reason column (existing tables updated via ALTER at deployment)
  migrations.push({
    table: TOOL_CALL_TABLE,
    column: "reject_reason",
    type: "LowCardinality(String) DEFAULT ''",
  });

  let ok = 0;
  let failed = 0;
  for (const m of migrations) {
    try {
      await client.command({
        query: `ALTER TABLE ${m.table} ADD COLUMN IF NOT EXISTS ${m.column} ${m.type}`,
        clickhouse_settings: { wait_end_of_query: 1 },
      });
      ok++;
    } catch (err: unknown) {
      failed++;
      log.warn("clickhouse.migrate.column_failed", {
        table: m.table,
        column: m.column,
        err: err instanceof Error ? err.message : String(err),
      });
    }
  }
  log.info("clickhouse.migrate.done", {
    ok,
    failed,
    total: migrations.length,
  });
}

/** ClickHouse timestamp target timezone offset (hours). 8 = China Standard Time (UTC+8). */
const CH_UTC_OFFSET_HOURS = 8;

/**
 * Convert an ISO 8601 UTC timestamp to a ClickHouse DateTime64 string in
 * China Standard Time (UTC+8).
 *
 * Caller uses `new Date().toISOString()` to generate ISO timestamp (always UTC, with "Z").
 * ClickHouse `timestamp` column is declared as `DateTime64(3, 'Asia/Shanghai')`, and un-offset strings
 * are parsed as Asia/Shanghai on insertion. Thus we advance the UTC wall clock by 8 hours first
 * to obtain "Beijing wall-clock digits" — ensuring that after ClickHouse parses it back, the **absolute epoch is correct**
 * (epoch unchanged) while display and time functions (now() / toStartOfDay() / toDate()) all operate in Beijing Time.
 *
 * Input:  "2026-06-16T10:00:00.000Z"  (UTC)
 * Output: "2026-06-16 18:00:00.000"   (Beijing wall-clock; parsing back with column timezone yields original UTC epoch)
 */
function toChTimestamp(iso: string): string {
  const ms = Date.parse(iso);
  if (Number.isNaN(ms)) {
    // Fallback to un-offset string formatting on parse failure (best-effort to prevent data loss).
    return iso.replace("T", " ").replace("Z", "").slice(0, 23);
  }
  const shifted = new Date(ms + CH_UTC_OFFSET_HOURS * 60 * 60 * 1000);
  return shifted.toISOString().replace("T", " ").replace("Z", "").slice(0, 23);
}

function num(v: unknown): number {
  return typeof v === "number" ? v : 0;
}

/** Sanity cap for credit values. A single request should never plausibly
 *  produce credit exceeding this value; anything above indicates a bug in
 *  pricing config or upstream usage payload.
 */
const CREDIT_SANITY_CAP = 1_000_000;

/**
 * Detect whether a computed credit value is anomalous and should be routed
 * to the raw traceability table instead of trusted for billing.
 *
 * Triggers:
 *   - NaN / Infinity / -Infinity (arithmetic broke somewhere)
 *   - Negative values (pricing bug or negative token counts)
 *   - Values > CREDIT_SANITY_CAP (misconfigured pricing or malformed upstream usage)
 *
 * Boundary: exactly CREDIT_SANITY_CAP (1_000_000) is still considered normal.
 */
export function isCreditAnomalous(credit: number): boolean {
  if (!Number.isFinite(credit)) return true;
  if (credit < 0) return true;
  if (credit > CREDIT_SANITY_CAP) return true;
  return false;
}

/** Input shape accepted by writeClickHouse / buildClickHouseRow. */
export interface ClickHouseWriteEntry {
  timestamp: string;
  event: string;
  modelId: string;
  /** User identifier: user_id from auth/verify when enabled, or SHA-256(apiKey)[:8] fallback. */
  keyId: string;
  sessionKey?: string;
  turnSeq?: number;
  userInput?: string;
  upstreamUrl: string;
  stream: boolean;
  usage?: Record<string, unknown>;
  routedFrom?: string;
  /** Space/tenant ID extracted from /proxy/<spaceId>/... path. */
  spaceId?: string;
  /**
   * Upstream request id — from upstream response header `x-request-id` (returned by
   * OpenAI/Anthropic compatible gateways like tokenhub). Empty string when unreturned or unread.
   * Used for cross-system tracing: client x-request-id → proxy usage_logs.upstream_request_id
   * → upstream service logs.
   */
  upstreamRequestId?: string;
  /**
   * Opaque scalar counters from the optional request-preparation stage
   * (cost-guard). `preCompressTokens` / `postCompressTokens` feed the three
   * compression columns; the rest is carried to the JSONL log untouched.
   */
  extensionStats?: Record<string, unknown>;
  /** Pricing config for credit calculation (from config.yaml). */
  pricingConfig?: CreditPricingConfig;
}

/**
 * Compute expected credit saved by routing to a different model.
 * Only applies when event='usage' AND routed_from is non-empty.
 * credit_saved = credit_if_original_model - actual_credit
 */
function computeCreditSaved(
  entry: ClickHouseWriteEntry,
  usage: Record<string, unknown>,
): number {
  // Only for main usage events with routing
  if (entry.event !== "usage") return 0;
  if (!entry.routedFrom) return 0;

  // Compute what credit would have been if using the original model
  const creditIfOriginal = computeCreditDelta(
    usage,
    entry.pricingConfig,
    entry.routedFrom,
    entry.upstreamUrl,
  );
  // Actual credit (using the routed model)
  const actualCredit = computeCreditDelta(
    usage,
    entry.pricingConfig,
    entry.modelId,
    entry.upstreamUrl,
  );

  const saved = creditIfOriginal - actualCredit;
  return saved > 0 ? saved : 0;
}

/**
 * Read the compression token pair out of extensionStats.
 *
 * Both columns are written together or not at all: a post without a pre has no
 * denominator and would read as a 100% saving. Anything missing or non-finite
 * means the stage produced no measurement, which is recorded as three zeros
 * rather than a guess.
 */
function computeCompressTokens(
  extensionStats: Record<string, unknown> | undefined,
): { pre: number; post: number; saved: number } {
  const none = { pre: 0, post: 0, saved: 0 };
  if (!extensionStats) return none;
  const pre = extensionStats.preCompressTokens;
  const post = extensionStats.postCompressTokens;
  if (typeof pre !== "number" || typeof post !== "number") return none;
  if (!Number.isFinite(pre) || !Number.isFinite(post)) return none;
  if (pre < 0 || post < 0) return none;
  const saved = pre - post;
  return {
    pre: Math.floor(pre),
    post: Math.floor(post),
    saved: saved > 0 ? Math.floor(saved) : 0,
  };
}

/**
 * Pure mapper: usage log entry → ClickHouse row.
 * Returns null for error records (4xx/5xx upstream errors carry no real usage).
 * Parses cache tokens across Anthropic / OpenAI / DeepSeek usage formats.
 * Exported for unit testing.
 */
export function buildClickHouseRow(entry: ClickHouseWriteEntry): ClickHouseRow | null {
  const usage = entry.usage ?? {};
  if (usage.error) return null;

  const promptDetails = usage.prompt_tokens_details as Record<string, unknown> | undefined;
  const cacheCreation = usage.cache_creation as Record<string, unknown> | undefined;
  const cacheHit =
    num(usage.prompt_cache_hit_tokens) ||
    num(usage.cache_read_input_tokens) ||
    num(promptDetails?.cached_tokens);
  const cacheMiss = num(usage.prompt_cache_miss_tokens);
  const cacheWrite =
    num(usage.prompt_cache_write_tokens) ||
    num(usage.cache_creation_input_tokens);

  // prompt_tokens semantics: total input (including cache)
  //   - OpenAI / DeepSeek: take usage.prompt_tokens directly
  //   - TokenHub Anthropic: usage.input_tokens excludes cache, add back cache_hit + cache_write
  //     to get total input
  const inputTokens = num(usage.input_tokens);
  const promptTokens =
    num(usage.prompt_tokens) || (inputTokens + cacheHit + cacheWrite);
  const completionTokens = num(usage.completion_tokens) || num(usage.output_tokens);
  // total_tokens semantics: total tokens = input + output
  //   - OpenAI / DeepSeek: upstream provides usage.total_tokens directly
  //   - TokenHub Anthropic: no total_tokens field from upstream, fallback to promptTokens + completionTokens
  //     (promptTokens is already total input including cache)
  const totalTokens = num(usage.total_tokens) || (promptTokens + completionTokens);

  const compressTokens = computeCompressTokens(entry.extensionStats);

  return {
    timestamp: toChTimestamp(entry.timestamp),
    event: entry.event,
    session_key: entry.sessionKey ?? "",
    turn_seq: entry.turnSeq ?? 0,
    user_input: entry.userInput ?? "",
    model_id: entry.modelId,
    model_name: resolveModelName(entry.pricingConfig, entry.modelId),
    user_id: entry.keyId,
    upstream_url: entry.upstreamUrl,
    stream: entry.stream ? 1 : 0,
    prompt_tokens: promptTokens,
    completion_tokens: completionTokens,
    total_tokens: totalTokens,
    cache_hit_tokens: cacheHit,
    cache_miss_tokens: cacheMiss,
    cache_write_tokens: cacheWrite,
    // TokenHub Anthropic raw fields — do not merge with other formats
    input_tokens: inputTokens,
    cache_creation_ephemeral_5m_input_tokens: num(cacheCreation?.ephemeral_5m_input_tokens),
    cache_creation_ephemeral_1h_input_tokens: num(cacheCreation?.ephemeral_1h_input_tokens),
    credit: computeCreditDelta(usage, entry.pricingConfig, entry.modelId, entry.upstreamUrl),
    credit_saved: computeCreditSaved(entry, usage),
    routed_from: entry.routedFrom ?? "",
    space_id: entry.spaceId ?? "",
    source_tag: "proxy",
    host: HOST_ID,
    upstream_request_id: entry.upstreamRequestId ?? "",
    compress_tokens_saved: compressTokens.saved,
    pre_compress_tokens: compressTokens.pre,
    post_compress_tokens: compressTokens.post,
  };
}

/**
 * Determine if usage should be written to the raw traceability table.
 *
 * Returns the reason string when the usage should be captured raw:
 *   - 'non_tokenhub'    — upstream URL does not contain "tokenhub"
 *   - 'unknown_model'   — TokenHub but model is not in the pricing table
 *   - 'invalid_format'  — TokenHub but usage lacks input/output fields
 *   - 'invalid_credit'  — TokenHub with valid format & known model, but the
 *                         computed credit is anomalous (NaN/Inf/negative/>1e6),
 *                         indicating a bug in pricing config or upstream payload
 * Returns `null` for normal, recognized TokenHub usage (no raw record needed).
 *
 * Priority (short-circuit): non_tokenhub → unknown_model → invalid_format → invalid_credit → null
 *
 * Exported for unit testing.
 */
export function getRawUsageReason(
  upstreamUrl: string,
  usage: Record<string, unknown> | null | undefined,
  pricingConfig: CreditPricingConfig | null | undefined,
  modelId?: string,
): string | null {
  if (!usage || Object.keys(usage).length === 0) return null;

  // Non-TokenHub → always write raw
  if (!/tokenhub/i.test(upstreamUrl)) return "non_tokenhub";

  // TokenHub but model not in pricing table
  if (modelId && pricingConfig && !getModelPricing(pricingConfig, modelId)) {
    return "unknown_model";
  }

  // TokenHub but missing expected fields
  const hasInput =
    typeof usage.input_tokens === "number" || typeof usage.prompt_tokens === "number";
  const hasOutput =
    typeof usage.output_tokens === "number" || typeof usage.completion_tokens === "number";
  if (!hasInput || !hasOutput) return "invalid_format";

  // TokenHub, valid format, known model — but credit calculation produced anomalous value.
  // We recompute here (not passed in) to keep this function callable from writeClickHouse
  // without threading the credit through. Extra compute is cheap (< 1μs).
  const credit = computeCreditDelta(usage, pricingConfig, modelId, upstreamUrl);
  if (isCreditAnomalous(credit)) return "invalid_credit";

  return null; // Normal TokenHub usage, no need for raw table
}

/** Pure mapper: usage log entry + reason → raw usage row. Exported for unit testing. */
export function buildRawUsageRow(
  entry: ClickHouseWriteEntry,
  reason: string,
): ClickHouseRawUsageRow {
  return {
    timestamp: toChTimestamp(entry.timestamp),
    model_id: entry.modelId,
    model_name: resolveModelName(entry.pricingConfig, entry.modelId),
    key_id: entry.keyId,          // Backwards compatibility (legacy usage_raw table still uses key_id as part of primary key)
    user_id: entry.keyId,          // New column (aligned with main table); double-write relying on JSONEachRow fault tolerance
    session_key: entry.sessionKey ?? "",
    turn_seq: entry.turnSeq ?? 0,
    user_input: entry.userInput ?? "",
    upstream_url: entry.upstreamUrl,
    stream: entry.stream ? 1 : 0,
    usage: JSON.stringify(entry.usage ?? {}),
    reason,
    routed_from: entry.routedFrom ?? "",
    space_id: entry.spaceId ?? "",
    source_tag: "proxy",
    host: HOST_ID,
    upstream_request_id: entry.upstreamRequestId ?? "",
  };
}

/**
 * Pure mapper: build a raw-table row for a **failed credit report** scenario.
 *
 * Reason is fixed to `"report_failed"`. The error detail (HTTP status / timeout
 * / upstream code message) is embedded into the usage JSON under a meta field
 * `__report_error`, so the raw table's `usage` column self-contains everything
 * an ops user needs to reconstruct the failure without a JOIN.
 *
 * Row shape is identical to `buildRawUsageRow` output, allowing it to be
 * appended to the same `usage_raw` table and flushed by `flushRaw`.
 */
export function buildFailedReportRawRow(
  entry: ClickHouseWriteEntry,
  errorDetail: string,
): ClickHouseRawUsageRow {
  const usageWithError = {
    ...(entry.usage ?? {}),
    __report_error: errorDetail,
  };
  return {
    timestamp: toChTimestamp(entry.timestamp),
    model_id: entry.modelId,
    model_name: resolveModelName(entry.pricingConfig, entry.modelId),
    key_id: entry.keyId,
    user_id: entry.keyId,
    session_key: entry.sessionKey ?? "",
    turn_seq: entry.turnSeq ?? 0,
    user_input: entry.userInput ?? "",
    upstream_url: entry.upstreamUrl,
    stream: entry.stream ? 1 : 0,
    usage: JSON.stringify(usageWithError),
    reason: "report_failed",
    routed_from: entry.routedFrom ?? "",
    space_id: entry.spaceId ?? "",
    source_tag: "proxy",
    host: HOST_ID,
    upstream_request_id: entry.upstreamRequestId ?? "",
  };
}

/**
 * Enqueue a "credit report failed" raw record to the traceability table.
 *
 * Fire-and-forget: never throws, no-op when ClickHouse disabled or `rawTable`
 * not configured. Uses the same `rawBuffer` and `flushRaw` machinery as
 * `writeClickHouse`, so retries/overflow protection apply automatically.
 *
 * Call from handlers when `tryReportCreditFromPath` returns `attempted && !ok`.
 */
export function writeFailedReportRaw(
  entry: ClickHouseWriteEntry,
  errorDetail: string,
): void {
  if (disabled || !config || !config.rawTable) return;
  try {
    rawBuffer.push(buildFailedReportRawRow(entry, errorDetail));
    if (rawBuffer.length >= (config?.flushThreshold ?? 50)) {
      void flushRaw();
    }
  } catch {
    // Silent — never block business logic.
  }
}

/**
 * Write a usage log entry to ClickHouse (buffered, async).
 * Fire-and-forget — never throws.
 */
export function writeClickHouse(entry: ClickHouseWriteEntry): void {
  if (disabled || !config) return;

  try {
    // Raw usage traceability (only when rawTable is configured).
    if (config.rawTable) {
      const rawReason = getRawUsageReason(
        entry.upstreamUrl,
        entry.usage,
        entry.pricingConfig,
        entry.modelId,
      );
      if (rawReason) {
        rawBuffer.push(buildRawUsageRow(entry, rawReason));
        if (rawBuffer.length >= (config?.flushThreshold ?? 50)) {
          void flushRaw();
        }
      }
    }

    const row = buildClickHouseRow(entry);
    if (!row) return;

    buffer.push(row);

    if (buffer.length >= (config?.flushThreshold ?? 50)) {
      void flush();
    }
  } catch {
    // Silent — never block business logic.
  }
}

/** Re-enqueue failed rows for retry, capping buffer to prevent unbounded growth. */
function requeue(rows: ClickHouseRow[]): void {
  buffer.unshift(...rows);
  if (buffer.length > 10000) {
    const dropped = buffer.length - 5000;
    buffer = buffer.slice(buffer.length - 5000);
    log.warn("clickhouse.buffer.overflow", { dropped });
  }
}

/** Re-enqueue failed raw rows for retry, capping buffer to prevent unbounded growth. */
function requeueRaw(rows: ClickHouseRawUsageRow[]): void {
  rawBuffer.unshift(...rows);
  if (rawBuffer.length > 10000) {
    const dropped = rawBuffer.length - 5000;
    rawBuffer = rawBuffer.slice(rawBuffer.length - 5000);
    log.warn("clickhouse.rawBuffer.overflow", { dropped });
  }
}

/**
 * Flush buffered rows to ClickHouse.
 * Returns a promise; callers may ignore it for fire-and-forget.
 */
export async function flush(): Promise<void> {
  if (!config || !client || buffer.length === 0) return;

  const rows = buffer.splice(0);
  try {
    await client.insert({
      table: config.table,
      values: rows,
      format: "JSONEachRow",
      clickhouse_settings: { async_insert: 1, wait_for_async_insert: 1 },
    });
    log.debug("clickhouse.flush.ok", { rows: rows.length });
  } catch (err: unknown) {
    log.error(
      "clickhouse.flush.error",
      { rows: rows.length },
      err instanceof Error ? err : new Error(String(err)),
    );
    requeue(rows);
  }
}

/**
 * Flush buffered raw usage rows to ClickHouse.
 * Returns a promise; callers may ignore it for fire-and-forget.
 */
export async function flushRaw(): Promise<void> {
  if (!config || !client || !config.rawTable || rawBuffer.length === 0) return;

  const rows = rawBuffer.splice(0);
  try {
    await client.insert({
      table: config.rawTable,
      values: rows,
      format: "JSONEachRow",
      clickhouse_settings: { async_insert: 1, wait_for_async_insert: 1 },
    });
    log.debug("clickhouse.flushRaw.ok", { rows: rows.length });
  } catch (err: unknown) {
    log.error(
      "clickhouse.flushRaw.error",
      { rows: rows.length },
      err instanceof Error ? err : new Error(String(err)),
    );
    requeueRaw(rows);
  }
}

/**
 * Graceful shutdown: stop timer, flush remaining buffer, close client.
 */
export async function shutdownClickHouse(): Promise<void> {
  if (flushTimer) {
    clearInterval(flushTimer);
    flushTimer = null;
  }
  await flush();
  await flushRaw();
  // Internal telemetry buffers (see §7.1)
  await flushSessionInit().catch(() => {});
  await flushToolCall().catch(() => {});
  if (client) {
    await client.close().catch(() => {});
    client = null;
  }
}

// ════════════════════════════════════════════════════════════════════════════
// Internal Usage Telemetry — Team memory internal usage telemetry
// See docs/design/2026-08-03-internal-usage-telemetry-plan.md for details
//
// Two new tables: session_init_logs / tool_call_logs
// Three generic helpers: createTableIfNotExists / enqueueRow / flushBuffer /
//                requeueWithOverflowGuard
//
// Hard constraints (§7.-1):
//   1. All write*Row functions return void synchronously and NEVER throw
//   2. Internal helpers also never throw (enqueueRow is completely silent except when threshold triggers flush)
//   3. Legacy code paths (writeClickHouse/flush/writeFailedReportRaw) remain untouched
// ════════════════════════════════════════════════════════════════════════════

// ── §9 Decision Constants ───────────────────────────────────────────────────

/** request_body truncation length (same specification as usage_logs.user_input) */
const TOOL_CALL_BODY_MAX_BYTES = 512;
/** bypass_reason truncation length (prevents column cardinality explosion from log changes) */
const BYPASS_REASON_MAX_CHARS = 128;
/** reject_reason truncation length (symmetric with bypass_reason; LowCardinality maintains stable cardinality) */
const REJECT_REASON_MAX_CHARS = 128;
/** Table names (shared between DDL + insert) */
const SESSION_INIT_TABLE = "session_init_logs";
const TOOL_CALL_TABLE = "tool_call_logs";
/** TTL (days) — 90 days is sufficient for internal observability */
const TELEMETRY_TTL_DAYS = 90;

// ── Type Definitions ────────────────────────────────────────────────────────

/** Raw input structure for session_init row passed by telemetry points (before row construction). */
export interface SessionInitLogInput {
  /** ISO 8601 UTC time string (`new Date().toISOString()`) */
  timestamp: string;
  /** Proxy session isolation key (compositeKey / x-conversation-id fallback) */
  sessionKey: string;
  /** Kernel tenant / instance ID (from sessionInfo.space_id) */
  spaceId?: string;
  /** User / team / agent ID (may be empty on bypass) */
  userId?: string;
  teamId?: string;
  agentId?: string;
  /** "claude-code" | "codebuddy" */
  agentSource: string;
  /** Actual value of state.bypassed */
  bypassed: boolean;
  /** First sentence of original log in init.ts (truncated to 128 characters) */
  bypassReason: string;
  /** Fixed as "initialized", extensible if more terminal states are added */
  finalStatus: string;
}

/** Final shape of one row in ClickHouse `session_init_logs` table. */
export interface SessionInitLogRow {
  timestamp: string;
  session_key: string;
  space_id: string;
  user_id: string;
  team_id: string;
  agent_id: string;
  agent_source: string;
  bypassed: number;
  bypass_reason: string;
  final_status: string;
  source_tag: string;
  host: string;
}

/** Raw input structure for tool_call row passed by telemetry points. */
export interface ToolCallLogInput {
  timestamp: string;
  sessionKey: string;
  turnSeq?: number;
  spaceId?: string;
  userId?: string;
  teamId?: string;
  agentId?: string;
  agentSource: string;
  /** 'model_intent' | 'bridge_call' */
  kind: string;
  /** 'memory-bridge' | 'skill-bridge' | '' (left empty for intent side) */
  bridgeSource?: string;
  /** function.name / tool_use.name in model SSE (left empty for bridge_call side) */
  initiatedTool?: string;
  /** Sub string forwarded by bridge, e.g. "atomic/search" (left empty for intent side) */
  executedEndpoint: string;
  /** Sanitized body content (truncated to 512 bytes) */
  requestBody: string;
  /** Upstream HTTP status (filled as 0 for intent side) */
  upstreamStatus?: number;
  /** Upstream latency in milliseconds (filled as 0 for intent side) */
  elapsedMs?: number;
  /**
   * Pre-check failure reason (proxy layer rejected request, failed to reach upstream).
   * Empty string = request entered upstream fetch phase (success or 4xx/5xx both take this path).
   * Non-empty = early exit on pre-check (enums: unknown_path / subpath_forbidden / method_not_allowed /
   * content_type_invalid / missing_conversation_id / session_not_initialized /
   * write_ops_disabled / body_not_object / invalid_json_body).
   * Symmetric with session_init.bypass_reason, truncated to REJECT_REASON_MAX_CHARS.
   */
  rejectReason?: string;
}

/** Final shape of one row in ClickHouse `tool_call_logs` table. */
export interface ToolCallLogRow {
  timestamp: string;
  session_key: string;
  turn_seq: number;
  space_id: string;
  user_id: string;
  team_id: string;
  agent_id: string;
  agent_source: string;
  kind: string;
  bridge_source: string;
  initiated_tool: string;
  executed_endpoint: string;
  request_body: string;
  request_body_hash: string;
  upstream_status: number;
  elapsed_ms: number;
  reject_reason: string;
  source_tag: string;
  host: string;
}

// ── Pure builders (side-effect free, unit-testable) ───────────────────────

/** Compute first 16 hex characters of body sha256 (for TopN GROUP BY deduplication). Returns empty string for empty body. */
function bodyHash16(body: string): string {
  if (!body) return "";
  return createHash("sha256").update(body).digest("hex").slice(0, 16);
}

/** Construct session_init row; pure function for testability. */
export function buildSessionInitLogRow(input: SessionInitLogInput): SessionInitLogRow {
  const reason = (input.bypassReason ?? "").slice(0, BYPASS_REASON_MAX_CHARS);
  return {
    timestamp: toChTimestamp(input.timestamp),
    session_key: input.sessionKey ?? "",
    space_id: input.spaceId ?? "",
    user_id: input.userId ?? "",
    team_id: input.teamId ?? "",
    agent_id: input.agentId ?? "",
    agent_source: input.agentSource,
    bypassed: input.bypassed ? 1 : 0,
    bypass_reason: reason,
    final_status: input.finalStatus,
    source_tag: "proxy",
    host: HOST_ID,
  };
}

/** Construct tool_call row; pure function for testability. */
export function buildToolCallLogRow(input: ToolCallLogInput): ToolCallLogRow {
  const body = (input.requestBody ?? "").slice(0, TOOL_CALL_BODY_MAX_BYTES);
  return {
    timestamp: toChTimestamp(input.timestamp),
    session_key: input.sessionKey ?? "",
    turn_seq: input.turnSeq ?? 0,
    space_id: input.spaceId ?? "",
    user_id: input.userId ?? "",
    team_id: input.teamId ?? "",
    agent_id: input.agentId ?? "",
    agent_source: input.agentSource,
    kind: input.kind,
    bridge_source: input.bridgeSource ?? "",
    initiated_tool: input.initiatedTool ?? "",
    executed_endpoint: input.executedEndpoint,
    request_body: body,
    request_body_hash: bodyHash16(body),
    upstream_status: input.upstreamStatus ?? 0,
    elapsed_ms: input.elapsedMs ?? 0,
    reject_reason: (input.rejectReason ?? "").slice(0, REJECT_REASON_MAX_CHARS),
    source_tag: "proxy",
    host: HOST_ID,
  };
}

// ── Generic helpers (three thin functions replacing copy-paste templates) ─────

/**
 * Forward DDL to client.command. Extracted to eliminate
 * `client.command({ query, clickhouse_settings: { wait_end_of_query: 1 } })`
 * template duplication. Exceptions propagate upward to let ensureClickHouse record in startup log.
 */
export async function createTableIfNotExists(
  ch: ClickHouseClient,
  ddl: string,
): Promise<void> {
  await ch.command({
    query: ddl,
    clickhouse_settings: { wait_end_of_query: 1 },
  });
}

/**
 * Generic enqueue + threshold-triggered flush (fire-and-forget).
 *
 * - Two-layer internal try/catch: one push fallback, one flushFn throw (async Promise unawaited).
 * - Never throws to caller.
 */
export function enqueueRow<T>(
  buf: T[],
  row: T,
  flushFn: () => Promise<void>,
  threshold: number,
): void {
  try {
    buf.push(row);
    if (buf.length >= threshold) {
      // fire-and-forget; error logged in flushBuffer, with .catch() fallback
      void flushFn().catch(() => { /* never throw */ });
    }
  } catch {
    // Extreme case: buffer itself corrupted — keep business logic unaffected
  }
}

/**
 * Generic flush: drain buffer → batch insert → call requeueFn on failure.
 *
 * - no-op when client is null / buf is empty
 * - buf emptied via splice(0) on success
 * - on failure rows extracted from buf → passed to requeueFn; resolves (does not reject) after log.error
 */
export async function flushBuffer<T>(
  buf: T[],
  ch: ClickHouseClient | null,
  tableName: string,
  requeueFn: (rows: T[]) => void,
  logLabel: string,
): Promise<void> {
  if (!ch || buf.length === 0) return;
  const rows = buf.splice(0);
  try {
    await ch.insert({
      table: tableName,
      values: rows,
      format: "JSONEachRow",
      clickhouse_settings: { async_insert: 1, wait_for_async_insert: 1 },
    });
    log.debug(`${logLabel}.flush.ok`, { rows: rows.length });
  } catch (err: unknown) {
    log.error(
      `${logLabel}.flush.error`,
      { rows: rows.length },
      err instanceof Error ? err : new Error(String(err)),
    );
    try {
      requeueFn(rows);
    } catch {
      // requeue also failed → discard; at least avoid rethrowing and dragging down business logic
    }
  }
}

/**
 * Re-queue + overflow protection: when buffer exceeds 10,000, drop oldest half and keep 5,000.
 *
 * Return value is new buffer reference (may be same array or newly sliced array).
 * Caller must reassign return value back to their buffer variable.
 */
export function requeueWithOverflowGuard<T>(
  buf: T[],
  failedRows: T[],
  logLabel: string,
): T[] {
  try {
    buf.unshift(...failedRows);
    if (buf.length > 10000) {
      const dropped = buf.length - 5000;
      const trimmed = buf.slice(buf.length - 5000);
      log.warn(logLabel, { dropped });
      return trimmed;
    }
    return buf;
  } catch {
    return buf;
  }
}

// ── Session Init writer ─────────────────────────────────────────────────────

let sessionInitBuffer: SessionInitLogRow[] = [];

function requeueSessionInit(rows: SessionInitLogRow[]): void {
  sessionInitBuffer = requeueWithOverflowGuard(
    sessionInitBuffer,
    rows,
    "clickhouse.sessionInit.overflow",
  );
}

async function flushSessionInit(): Promise<void> {
  await flushBuffer(
    sessionInitBuffer,
    client,
    SESSION_INIT_TABLE,
    requeueSessionInit,
    "clickhouse.sessionInit",
  );
}

/**
 * Write one session_init record (fire-and-forget, never throws).
 * no-op when CH is disabled/uninitialized; silently swallow construction exceptions.
 */
export function writeSessionInitRow(input: SessionInitLogInput): void {
  if (disabled || !config) return;
  try {
    const row = buildSessionInitLogRow(input);
    enqueueRow(
      sessionInitBuffer,
      row,
      flushSessionInit,
      config?.flushThreshold ?? 50,
    );
  } catch {
    // Never block business logic
  }
}

// ── Tool Call writer ────────────────────────────────────────────────────────

let toolCallBuffer: ToolCallLogRow[] = [];

function requeueToolCall(rows: ToolCallLogRow[]): void {
  toolCallBuffer = requeueWithOverflowGuard(
    toolCallBuffer,
    rows,
    "clickhouse.toolCall.overflow",
  );
}

async function flushToolCall(): Promise<void> {
  await flushBuffer(
    toolCallBuffer,
    client,
    TOOL_CALL_TABLE,
    requeueToolCall,
    "clickhouse.toolCall",
  );
}

/**
 * Write one tool_call record (fire-and-forget, never throws).
 * no-op when CH is disabled/uninitialized; silently swallow construction exceptions.
 */
export function writeToolCallRow(input: ToolCallLogInput): void {
  if (disabled || !config) return;
  try {
    const row = buildToolCallLogRow(input);
    enqueueRow(
      toolCallBuffer,
      row,
      flushToolCall,
      config?.flushThreshold ?? 50,
    );
  } catch {
    // Never block business logic
  }
}

// ── DDL Constants (appended to ensureClickHouse via createTableIfNotExists) ──

/** DDL for session_init_logs (internal usage telemetry §3.1) */
export function sessionInitTableDdl(): string {
  const ttlClause = TELEMETRY_TTL_DAYS > 0
    ? `TTL toDateTime(timestamp) + INTERVAL ${TELEMETRY_TTL_DAYS} DAY`
    : "";
  return [
    `CREATE TABLE IF NOT EXISTS ${SESSION_INIT_TABLE} (`,
    "  timestamp DateTime64(3, 'Asia/Shanghai'),",
    "  session_key String,",
    "  space_id String,",
    "  user_id String,",
    "  team_id String,",
    "  agent_id String,",
    "  agent_source LowCardinality(String),",
    "  bypassed UInt8,",
    "  bypass_reason String,",
    "  final_status LowCardinality(String),",
    "  source_tag LowCardinality(String) DEFAULT 'proxy',",
    "  host LowCardinality(String)",
    ") ENGINE = MergeTree()",
    "ORDER BY (space_id, timestamp)",
    ttlClause,
  ].filter(Boolean).join("\n");
}

/** DDL for tool_call_logs (internal usage telemetry §3.2) */
export function toolCallTableDdl(): string {
  const ttlClause = TELEMETRY_TTL_DAYS > 0
    ? `TTL toDateTime(timestamp) + INTERVAL ${TELEMETRY_TTL_DAYS} DAY`
    : "";
  return [
    `CREATE TABLE IF NOT EXISTS ${TOOL_CALL_TABLE} (`,
    "  timestamp DateTime64(3, 'Asia/Shanghai'),",
    "  session_key String,",
    "  turn_seq UInt32 DEFAULT 0,",
    "  space_id String,",
    "  user_id String,",
    "  team_id String DEFAULT '',",
    "  agent_id String DEFAULT '',",
    "  agent_source LowCardinality(String),",
    "  kind LowCardinality(String),",
    "  bridge_source LowCardinality(String) DEFAULT '',",
    "  initiated_tool String,",
    "  executed_endpoint String,",
    "  request_body String CODEC(ZSTD(3)),",
    "  request_body_hash FixedString(16) DEFAULT '',",
    "  upstream_status UInt16 DEFAULT 0,",
    "  elapsed_ms UInt32 DEFAULT 0,",
    // Proxy pre-check failure reason; empty string when upstream responded or errored; symmetric with session_init.bypass_reason.
    "  reject_reason LowCardinality(String) DEFAULT '',",
    "  source_tag LowCardinality(String) DEFAULT 'proxy',",
    "  host LowCardinality(String)",
    ") ENGINE = MergeTree()",
    "ORDER BY (space_id, session_key, timestamp)",
    ttlClause,
  ].filter(Boolean).join("\n");
}
