replacements = {
    "MemoryCore/src/metadata/service/metadata-service.ts": {
        2: " * MetadataService - Metadata business orchestration layer.",
        4: " * Corresponds to design doc §2 / §7 / §10. Overlays business constraints on top of IMetadataStore:",
        5: " *   - createAgent/createTask/createAsset verifies team existence",
        6: " *   - createTask linkAgents verifies agent belongs to the same team",
        7: " *   - setAgentFixedAssets uses canBindAsset to verify visibility",
        8: " *   - listAgentFixedAssetsWithDetail aggregates agent + detail + (optional) visibility filter + touchUsage",
        9: " *   - checkAssetPermission lazy loads ACL (bypasses table lookup when role defaults cover it)",
        10: " *   - user_key generation/refresh",
        12: " * Agnostic to specific backend (SQLite / MongoDB), ensuring storage is switchable.",
        94: "// ── Default Agent / Team Constants ──",
        97: 'const DEFAULT_TEAM_DESCRIPTION = "Default team created automatically upon system initialization, used to store default agents";',
        100: 'const DEFAULT_AGENT_DESCRIPTION = "Default agent, can handle common development tasks and daily collaboration.";',
        102: "// prompt concatenation format is identical to frontend manual Agent creation:",
        110: "// metadata_json stores the split role_prompt / rules_prompt,",
        111: "// format matches the 'ui' namespace in frontend writeAgentUiMeta / readAgentUiMeta,",
        112: "// ensuring that 'Role Positioning prompt' and 'Rule Fixing prompt' are displayed separately on the Agent details page.",
        120: "/** Business validation error, with code mappable to HTTP status. */",
        132: " * Clears the chat_memory content (L0/L1/L2/L3 + vectors + files) for a specific (team, agent).",
        134: " * Implemented and injected by gateway assembly (see MetadataService.setChatMemoryContentCleaner),",
        135: " * because content is stored in IMemoryStore / StorageAdapter, not in metadata store.",
        184: "  /** Optional type filter: only return asset_type matching this list; omitted / empty array = no filter. */",
        212: "   * Optional visibility whitelist, used for secondary filtering after permission check.",
        213: "   * Example: `[\"team\"]` = only return team visible (used for management page \"team assets\" tab);",
        214: "   * omitted = return all accessible (including own private).",
        215: "   * Purpose: Prevents frontend from getting unneeded data in the HTTP response (security + reduced payload).",
        240: "   * In-process LRU cache: set of confirmed chat_memory asset ids (existing in store).",
        242: "   * A hit skips three DB roundtrips: getAssetById + createAsset + addAgentFixedAsset.",
        243: "   * A miss goes through the full ensure process and writes to cache upon success. Across processes/pods, each maintains its own",
        244: "   * LRU — consistency is guaranteed by store primary key constraints.",
        246: "   * Uses Map insertion order + evicts oldest item when limit reached. Not strictly LRU (no touch upon read),",
        247: "   * but sufficient for this 'write once, hit forever' scenario: once confirmed existing, the entry either continues",
        248: "   * to hit or gets pushed out by newer team+agent and goes through DB again — cold eviction cost is just one DB query.",
        249: "   * maxSize is controlled by CHAT_MEMORY_ENSURE_CACHE_SIZE.",
        255: "   * In-process LRU for skill asset registration: key = skill_id (i.e. asset_id).",
        256: "   * Semantics identical to ensuredChatMemoryAssets, short-circuits repeated create+bind in ensureSkillAsset.",
        261: "  /** Chat_memory content cleaner injected by gateway; if not injected, archiving only deletes asset without clearing content. */",
        291: "   * Inject 'chat_memory content cleaner'.",
        293: "   * Why use an optional hook instead of direct store dependency: metadata layer only holds IMetadataStore",
        294: "   * (metadata) and cannot access IMemoryStore / StorageAdapter (L0-L3 content). Archiving",
        295: "   * an Agent needs to clear its memory content, which requires the gateway assembly to inject the cleaning capability",
        296: "   * — same pattern as setConfigParamService, keeping dependency direction inverted.",
        298: "   * Without injection, archiveAgent degrades to original behavior (only deletes asset, does not clear content), thus",
        299: "   * scenarios not assembling this hook (unit tests / migration scripts) are unaffected.",
        305: "  /** memory static key only used for auth/verify body, cannot be used for Header auth. */",
        327: "  /** internal: list users by instance with pagination (includes system_admin, no masking). */",
        338: "  /** Validate user existence, otherwise throw not_found. */",
        376: "  // User (including user_key generation/refresh)",
        386: "    // Core operation: create admin user",
        392: "    // Auxiliary operation: auto-create default Team and Agent (failure does not block core flow)",
        414: "          `[init-admin] Default Agent creation failed, skipped (user=${created.user_id})`,",
        420: "        `[init-admin] Default Team creation failed, skipped (user=${created.user_id})`,",
        433: "   * Only for /v3/meta/user/create-with-key: allows system_admin to explicitly specify user_key when creating account.",
        435: "   * Two-layer deduplication:",
        436: "   *   1. Upfront getUserByKey: fast failure on normal path, no transaction entered",
        437: "   *   2. Store layer UNIQUE constraint (DuplicateUserKeyError): TOCTOU / concurrency fallback",
        439: "   * Router layer must call assertCanManageUsers first for auth.",
        462: "  /** Fallback to default values (local / user_id) when auth_provider / external_id not passed. */",
        598: "  /** @deprecated use listUsersForCaller */",
        661: "  /** Validate user_key and return corresponding user (returns null if invalid). */",
        717: "  /** Validate caller has access to this key (self, system_admin or bootstrap), returns masked details. */",
        813: "    // owner is fixed to admin by createTeam; prevent downgrade via add upsert, otherwise",
        814: "    // 'still owner but role!=admin' happens - 403 when acting as admin or team-member/add.",
        826: "    // Core operation: add user to Team",
        846: "  // Agent (validate team existence)",
        851: "    // Outside the same transaction boundary of agent creation, immediately mint the agent's chat_memory asset +",
        852: "    // bind to fixed_assets. avoids Bug 2: asset doesn't exist when first conversation is triggered →",
        853: "    // profile-memory-injector first session prewarm falls back to tools-only,",
        854: "    // and under session_init caching strategy, L3 is never read during the session.",
        856: "    // Idempotent: ensureChatMemoryAsset uses no-op internally for existing asset / existing binding.",
        857: "    // Failure is non-fatal: agent created successfully, chat_memory is just 'prepared earlier',",
        858: "    // even if it fails here, the /conversation/add path will still retry ensure, hence only log warn here.",
        865: "      // No dedicated warn logger here (service layer only has PermCheckLogger.debug),",
        866: "      // use console.warn to be consistent with similar catch in v2-router.handleConversationAdd.",
        911: "   * Archive (soft close) agent.",
        913: "   * Order is critical — **clear content first, then delete asset**:",
        915: "   *   2. Clear the agent's chat_memory content (L0/L1/L2/L3 + vectors + files)",
        916: "   *   3. Delete its own chat_memory asset record (and cascade clear borrowed bindings from other agents)",
        918: "   * If the order is reversed (delete asset then clear content), once the asset record is gone, we can no longer locate",
        919: "   * (team, agent) from asset_id, and the content becomes **permanently unreachable orphan data**",
        920: "   * left in the database — this is exactly the issue fixed here.",
        922: "   * If content cleanup fails, **abort archiving** and throw upward: better to let caller retry than leave",
        923: "   * an inconsistent state of 'asset deleted, content remains'. When cleaner is not injected (unit tests / migration",
        924: "   * scripts), skip step 2 and degrade to original behavior.",
        944: "  // Task (validate team existence + linked agents in same team)",
        994: "  /** Archive (soft close) task: status → completed. */",
        1067: "  // Asset (main table only)",
        1087: "    // Clear ensure cache to avoid short-circuit falsely judging 'still exists' after deletion",
        1119: "   * Multiple agent fixed asset allocation summary. Missing agent / type filled with 0; items order matches requested agent_ids.",
        1120: "   * Optional asset_id: only count rows bound to this asset (used for bound_agent_count).",
        1166: "  // AgentFixedAsset (canBindAsset validation + detail aggregation)",
        1188: "   * Append an agent binding (keep existing bindings). Used for incremental scenarios like",
        1189: "   * auto-registering chat_memory asset; different from full replacement in setAgentFixedAssets.",
        1191: "   * Validation: agent / asset must both be in current instance; canBindAsset must pass.",
        1192: "   * Idempotency: store layer relies on (agent_id, asset_id) unique constraint, repeated calls have no side effects.",
        1209: "   * Idempotently ensure the chat_memory asset for (team, agent) exists and is bound to the agent.",
        1211: "   * First call will synchronously complete three things (strict order):",
        1215: "   *   3. Write to in-process LRU cache, subsequent requests for same (team, agent) short-circuit directly",
        1217: "   * Idempotency guarantees:",
        1218: "   *   - asset_id = chat_memory-{team}-{agent} is stable and deterministic",
        1219: "   *   - meta_assets.asset_id is primary key → concurrency create conflicts trigger readback",
        1220: "   *   - meta_agent_fixed_assets (agent_id, asset_id) is unique → repeated",
        1221: "   *     addAgentFixedAsset is absorbed by store layer as no-op",
        1223: "   * Failure strategy: This method **will throw errors** (agent_not_found / team_mismatch / DB failure).",
        1224: "   * Caller (handleConversationAdd in v2-router) is responsible for catch + logging warn only,",
        1225: "   * without blocking main flow conversation writing.",
        1233: "    // 1. Cache short-circuit: if confirmed exists, return lightweight placeholder directly (only query store if caller needs entity)",
        1234: "    //    In practice caller doesn't consume return value (fire-and-forget), doesn't query store on cache hit.",
        1238: "      // Cache is dirty (deleted externally) — clear and start over",
        1242: "    // 2. Fetch agent, get owner + team for create + canBindAsset",
        1243: "    //    Fetching agent first ensures team_mismatch validation in all paths, and later bind",
        1244: "    //    needs owner_user_id as created_by.",
        1260: "    // 3. Fetch or create asset: check if already in store first (cold start / created by other pod), otherwise create.",
        1261: "    //    createAsset primary key conflict = concurrency race, readback as fallback.",
        1285: "    // 4. Whether asset is newly created or pre-existing, **idempotently** append binding once.",
        1286: "    //    Previous attempt might have only completed create, failing at bind stage; bind has UNIQUE constraint, repeated",
        1287: "    //    calls have no side effects. Directly call store here skipping addAgentFixedAsset's repeated validation",
        1288: "    //    — we already queried agent / asset above.",
        1301: "  /** LRU-ish record: evict earliest written entry when limit reached. */",
        1312: "  //  Skill Asset — Same ensure pattern",
        1316: "   * Register skill asset and bind to agent. Same 5-step structure as ensureChatMemoryAsset:",
        1318: "   *   1. LRU short-circuit (key = skill_id, i.e. asset_id)",
        1319: "   *   2. Query agent to get owner + validate team",
        1320: "   *   3. Idempotent createAsset (asset_id = skill_id)",
        1321: "   *   4. Idempotent addAgentFixedAsset (injection_mode = reference)",
        1322: "   *   5. Record to LRU",
        1324: "   * Idempotency guarantees:",
        1325: "   *   - asset_id is external skill_id (core layer generates skl-xxxx), stable and unique",
        1326: "   *   - meta_assets.asset_id primary key → readback on concurrency create conflict",
        1327: "   *   - meta_agent_fixed_assets (agent_id, asset_id) UNIQUE → bind idempotent",
        1329: "   * Failure strategy:",
        1330: "   *   - v1 creation path (onSkillCreated context): throws exception to interrupt create,",
        1331: "   *     avoiding 'skill saved to DB but invisible in frontend' unrecoverable state",
        1332: "   *   - read self-healing path (onSkillAccessed context): handled via try/catch by caller,",
        1333: "   *     does not affect skill returning",
        1341: "    const assetId = params.skill_id; // skill_id === asset_id (convention)",
        1343: "    // 1. LRU short-circuit",
        1350: "    // 2. Fetch agent to get owner + validate team",
        1366: "    // 3. Idempotent createAsset",
        1368: "    // Default visibility = \"private\" (2026-07 change):",
        1369: "    //   - Newly created skill is strictly private, visible only to owner and team admin.",
        1370: "    //   - To make readable to everyone in team → user explicitly changes to 'shared' in management page (asset/update visibility=team).",
        1371: "    //   - To make readable to specific user/agent → use acl/grant + visibility=restricted.",
        1373: "    // Why not \"team\": Skill content often includes internal knowledge, scripts, credential comments, etc.,",
        1374: "    // \"visible to entire team by default\" is not secure enough for privacy-sensitive scenarios (e.g., skill for personal debugging).",
        1375: "    // Private → active sharing mindset is more intuitive.",
        1399: "    // 4. Idempotent addAgentFixedAsset",
        1412: "  /** LRU-ish record: evict earliest written entry when limit reached. */",
        1495: "  // Permission checking (lazy-loaded ACL)",
        1504: "    // owner short-circuit, no need to check members/ACL",
        1511: "    // Run through with empty ACL first: if role default matches, allow immediately, no table lookup needed",
        1524: "    // Only when 'passes prerequisite gate but role default doesn't cover' (no_permission) requires lazy-loaded ACL re-check",
        1540: "  /** Filter asset list accessible by user (offset pagination after permission aggregation). */",
        1546: "    // visibility whitelist (server-side filtering to prevent frontend from receiving restricted data)",
        1586: "          // visibility whitelist filtering (exclude before permission checking to save checkAssetPermission overhead)",
        1663: "   * Write permission for agent fixed assets: owner themselves, or team admin of the agent's team.",
        1664: "   * Used for cold start scenarios like 'admin mounts default Agent asset for new user' (referencing asset's",
        1665: "   * assertCallerIsAssetOwnerOrTeamAdmin precedent, allows team admin).",
        1726: "    // 'Add member' shouldn't be used to change own role; selecting self + role=member would downgrade admin.",
        1769: "    // owner themselves, or team admin of the team (admin creating default Agent for new user)",
        1879: "    // Skip owner check for non-existent ids (aligned with store layer idempotency success); existing ones must be owner.",
        1894: "   * Bulk upfront parsing for `/v3/chat-memory/clear`: maps asset_id to (team, agent).",
        1896: "   * Semantics (aligned with requirement 'reject bulk if any memory_id is invalid'):",
        1897: "   *   - Every id must exist and asset_type === \"chat_memory\";",
        1898: "   *   - Must be able to locate corresponding agent under the asset's team;",
        1899: "   *   - If any condition unmet, throws MetadataError immediately, bulk not executed.",
        1901: "   * **Does not perform user-level Owner check**: internal data plane trust model is Bearer +",
        1902: "   * x-tdai-service-id i.e., admin-level credentials (consistent with L0-L3 delete APIs).",
        1903: "   * \"Only asset Owner can operate\" is done by panel backend before forwarding.",
        1905: "   * Only performs validation and reading, **does not modify any asset fields** — clear only deletes content, leaves asset untouched.",
        1911: "    // Agent list for same team will be reused repeatedly in bulk scenario, cache by team once.",
        1945: "   * Fetch all agent_ids under a team (paginated traversal, max 100 per page).",
        1946: "   * Added hard limit to prevent abnormally large teams from exhausting memory.",
    },
    "MemoryCore/src/metadata/service/permission-checker.ts": {
        2: " * Permission checking pure functions.",
        4: " * Corresponds to design doc §10.3 (checkPermission, three-stage: owner+scope+grant)",
        5: " * and §10.4 (canBindAsset, fixed asset binding validation).",
        7: " * Design highlights:",
        8: " *   - Check sequence optimized as 'resource → owner → member → visibility → role default → ACL → deny',",
        9: " *     high-frequency scenarios (admin read-write / member read-only) pass at role default, no ACL table lookup needed.",
        10: " *   - Role default permissions are code-level hardcoded constants, no need to pre-configure data for roles.",
        11: " *   - Phase one allow-only model.",
        23: "  /** User's membership relationship under asset.team_id. */",
        26: "  /** All ACL records related to asset (lazy-loaded: provided by service only when reaching ACL step). */",
        28: "  /** Optional, passed when action='use' and caller is agent. */",
        47: "  // 1. Resource doesn't exist/archived",
        53: "  // 2. Owner has full permission",
        59: "  // 3. Not a team member",
        65: "  // 4. visibility restriction",
        68: "      // Private semantics (2026-07 change): strictly private, only owner_user_id can access.",
        69: "      // Team admin is not allowed either — because step 2 owner check already returned ALLOW,",
        70: "      // reaching here means current user is not owner, uniformly denied even if admin.",
        72: "      // Semantics explanation:",
        73: "      //   - private = personal private asset, no one in team can see (including admins)",
        74: "      //   - team    = shared with entire team (team members can read, owner/admin can write)",
        75: "      //   - restricted = strict ACL whitelist (handled in case below)",
        77: "      // Impact:",
        78: "      //   - list-accessible doesn't return others' private assets (effective for admins too)",
        79: "      //   - permission-checker.check returns DENY for admins accessing others' private assets",
        80: "      //   - If admin really needs to view, owner must actively switch to team or authorize via acl/grant",
        116: "  // 5. Role default permission (allows on match, can skip ACL query)",
        123: "  // 6. Explicit ACL (three subject types: user / team_role / agent)",
        142: " * Whether role default permission covers this action (service uses this to determine if lazy-loading ACL is needed).",
        143: " * Returning true means no ACL table lookup needed.",
        151: " * Check if Asset's visibility allows binding to specified Agent (§10.4).",
        152: " * Complementary to checkPermission: checkPermission manages 'who can operate on resource',",
        153: " * canBindAsset manages 'whether resource can be mounted to agent'.",
    },
    "MemoryCore/src/metadata/service/resolve-user-id.ts": {
        2: " * Resolves user_id or user_key to user_id (shared by auth/query APIs).",
    },
    "MemoryCore/src/metadata/service/user-visibility.ts": {
        2: " * system_admin external visibility: hidden by default in list/query APIs, visible only via bootstrap key or self.",
        8: "  /** When team-level list restricts member set, team admin can see normal users within it. */",
        20: "/** admin/system_admin can read all; normal users can only read themselves; system_admin account is hidden from others by default. */",
        27: "    // Only one system_admin per instance (design invariant); ctx.isSystemAdmin branch unreachable in prod, kept for defense.",
        36: "/** v3.1 public response: user_id / user_type / username / created_at. */",
    },
    "MemoryCore/src/metadata/store/mongodb-adapter.ts": {
        87: "/** E11000 on meta_user_keys.key_value (hits concurrency when caller explicitly specifies default_key_value). */",
    },
    "MemoryCore/src/metadata/utils/chat-memory-asset.ts": {
        2: " * chat_memory asset ID generation rules.",
        4: " * Convention: Each (team, agent) combination corresponds to **one** stable chat_memory asset, asset_id",
        5: " * is constructed from team_id and agent_id:",
        9: " * This deterministic ID makes the write path automatically idempotent — no matter how many times same (team, agent) is requested,",
        10: " * the calculated asset_id is identical, and store layer primary key constraints naturally intercept duplicate inserts.",
        12: " * Forward concatenation doesn't need reversing. `/v3/chat-memory/clear` needs to locate (team, agent) from asset_id",
        13: " * to clear content, but **does not split string** — team_id / agent_id internally",
        14: " * might contain `-`, splitting causes ambiguity. Reverse locating uniformly uses `resolveChatMemoryAgentId`:",
        15: " * concatenating asset's known team_id + candidate agent_id and comparing, confirming upon match.",
        18: "/** chat_memory asset ID prefix. */",
        21: "/** Stably generate a chat_memory asset ID corresponding to (team, agent). */",
        27: " * Find the agent_id matching assetId from candidate agent list.",
        29: " * Uses forward concatenation comparison instead of string splitting, so it's still correct when team_id / agent_id contains `-`.",
        31: " * @param assetId    chat_memory asset ID",
        32: " * @param teamId     team_id on the asset record (authoritative value, not guessed from assetId)",
        33: " * @param agentIds   candidate agent_id list under the team",
        34: " * @returns          matched agent_id; undefined if no match",
    },
    "MemoryCore/src/metadata/utils/crypto.ts": {
        2: " * User key and password hashing utilities.",
        4: " * Corresponds to design doc §5:",
        5: " *   - user_key: `sk-mem-` prefix + 24 byte(192bit) base64url random segment, external caller auth identifier",
        6: " *   - password: scrypt + per-user random salt + global pepper (irreversible hash)",
        8: " * pepper is injected via environment variable during deployment (see loadPasswordHashConfig).",
        9: " * From v3.1, metadata User domain no longer uses password hash; this module only retains generateUserKey and legacy hash tools.",
        16: " * Generate user key: `sk-mem-` prefix + 24 byte(192bit) base64url random segment.",
        18: " * base64url charset is `[A-Za-z0-9_-]`, safe for URL / HTTP Header / JSON.",
        19: " * 192bit entropy is far above collision boundary, global uniqueness guaranteed with `key_value` unique index.",
        27: "/** Generate random password (default 12 chars, charset: alphanumeric, underscore). */",
        37: "/** scrypt parameters and DB storage format prefix. */",
        55: " * Load password hash config from environment variables.",
        57: " * Environment variables:",
        58: " *   - TDAI_PASSWORD_PEPPER — base64 encoded 32 byte random value (required in service mode)",
        59: " *   - TDAI_PASSWORD_SCRYPT_N / _R / _P / _KEYLEN — optional scrypt parameters",
        61: " * @throws Throws exception when pepper is not configured or format is invalid.",
        102: " * Perform scrypt+pepper hash on plaintext password, returning self-describing string for DB storage.",
        104: " * Format: `$scrypt$N,r,p$<salt_b64>$<hash_b64>`",
        115: "/** Check if DB storage string is in scrypt hash format. */",
        121: " * Verify if plaintext password matches DB storage hash. Invalid format or mismatched parameters return false (no exception thrown).",
    },
    "MemoryCore/src/metadata/utils/external-asset-id.ts": {
        2: " * External asset ID generation (design §4.1.1 / API reference AssetEntity).",
        3: " * Metadata module does not generate asset_id; this tool is for caller and test use.",
        8: "/** `asset_type` → `asset_id` prefix (including part before subsequent `-`). */",
        16: "/** Generate standardized external asset ID, e.g. `skl-a3b9c1f2`. */",
    },
    "MemoryCore/src/metadata/utils/id-generator.ts": {
        2: " * Unique ID generation with business prefixes.",
        4: " * Corresponds to design doc §4 ID generation specification (v3.1):",
        5: " *   - Subject/resource entity: `{prefix}-{4-char timestamp Base36}{6-char random Base36}` (§4.4 Scheme A)",
        6: " *   - Relationship table: UUID v4 (`randomUUID()`)",
        16: "/** @deprecated Relationship tables use UUID in v3.1; keeping constant for old test migration reference. */",
        19: "/** Business entity ID prefix mapping (relationship tables have no prefix). */",
        31: "/** Encode non-negative integer to fixed-length Base36 (left-padded with 0). */",
        42: "/** Generate random Base36 string of length. */",
        52: " * Generate entity ID with prefix, e.g. `usr-3mfxa3b9c1`.",
        54: " * @param prefix Business prefix (see ID_PREFIX)",
        63: "/** Generate relationship table primary key (UUID v4). */",
        69: " * Validate ID legality.",
        71: " * @param id ID to validate",
        72: " * @param prefix Optional, when specified requires ID to start with `{prefix}-`; when omitted only validates non-empty",
        73: " *               (compatible with existing ULID format).",
    },
    "MemoryCore/src/metadata/utils/user-key.ts": {
        2: " * user_key masking and validity checking (multi-key model).",
        5: "/** user_key fixed prefix, used to identify ownership and key scanning. */",
        9: " * Generic sensitive string masking: first 8 chars + ellipsis, without exposing full secret.",
        10: " * Used for api-trace to mask generalized keys like password / token / authorization in logs.",
        19: " * user_key list/detail display masking: retains `sk-mem-` prefix + `****` + last 4 chars.",
        20: " * For example `sk-mem-<32 chars>...e5fG` → `sk-mem-****e5fG`.",
        30: "/** Whether active key has expired (expires_at is ISO string). */"
    }
}

import sys
for file_path, mapping in replacements.items():
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        for ln, txt in mapping.items():
            idx = ln - 1
            if idx < len(lines):
                # keep newline
                lines[idx] = txt + '\n'
        with open(file_path, 'w', encoding='utf-8') as f:
            f.writelines(lines)
        print(f"Updated {file_path}")
    except Exception as e:
        print(f"Error on {file_path}: {e}")
