#!/usr/bin/env bash
# Starts the proxy independently (context-proxy, port 8096).
#
# The proxy forwards requests upstream to PROXY_UPSTREAM_URL (independent of the memory-stack's MEMORY_LLM_*).
# The proxy calls memory:8420 for auth / skill / tdai memory injection; calls memory-hub:8125
# for sessionInit control plane. You can run proxy standalone but related capabilities will degrade / disable.
#
# Usage:
#   ./start-proxy.sh
#
# Requires the following proxy group parameters (defined in .env):
#   PROXY_UPSTREAM_URL / PROXY_UPSTREAM_API_KEY / PROXY_UPSTREAM_MODEL

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_lib.sh
source "$SCRIPT_DIR/_lib.sh"

load_env
require_vars \
  PROXY_IMAGE PROXY_PORT \
  PROXY_UPSTREAM_URL PROXY_UPSTREAM_API_KEY PROXY_UPSTREAM_MODEL

# Internal gateway credentials matching memory-core (defaults to local, only for local dev)
MEMORY_CORE_GATEWAY_API_KEY="${MEMORY_CORE_GATEWAY_API_KEY:-local}"

CONTAINER=tdai-proxy
NETWORK=tdai-memory-stack

if ! $DOCKER network inspect "$NETWORK" >/dev/null 2>&1; then
  info "Creating docker network $NETWORK"
  $DOCKER network create "$NETWORK" >/dev/null
fi

# Dependency check (non-blocking, warning only)
if ! $DOCKER ps --format '{{.Names}}' 2>/dev/null | grep -qx "tdai-memory-core"; then
  warn "memory-core container is not running, proxy's auth / tdai memory / skill injection will all degrade."
fi
if ! $DOCKER ps --format '{{.Names}}' 2>/dev/null | grep -qx "tdai-memory-hub"; then
  warn "memory-hub container is not running, proxy's sessionInit control plane is unreachable."
fi

pull_image "$PROXY_IMAGE"
rm_container_if_exists "$CONTAINER"

# The proxy only reads upstream URL / API key from YAML (ignores PROXY_UPSTREAM_URL env),
# so we generate a minimal config.yaml from .env and mount it to /data/config.yaml in the container.
# The container CMD is already [--config /data/config.yaml].
CONFIG_DIR="${PROXY_CONFIG_DIR:-$SCRIPT_DIR/.proxy-config}"
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/config.yaml"

# ── Three major capability flags (defaults to minimum viable; enables dependencies automatically when ON) ──
# PROXY_ENABLE_AUTH        : Client relies on x-tdai-user-key to route via core auth/verify → user_id
# PROXY_ENABLE_SESSION_INIT: Initial round triggers form for selecting team/agent/task; depends on auth+tdai
# PROXY_ENABLE_TDAI        : L2/L3 memory injection + L1 recall; depends on memory-core
# Convenience flag PROXY_FULL_STACK=1 to toggle all three on.
if [[ "${PROXY_FULL_STACK:-0}" == "1" ]]; then
  PROXY_ENABLE_AUTH=1
  PROXY_ENABLE_TDAI=1
  PROXY_ENABLE_SESSION_INIT=1
fi
PROXY_ENABLE_AUTH="${PROXY_ENABLE_AUTH:-0}"
PROXY_ENABLE_TDAI="${PROXY_ENABLE_TDAI:-0}"
PROXY_ENABLE_SESSION_INIT="${PROXY_ENABLE_SESSION_INIT:-0}"

# sessionInit depends on auth for user_id; opening sessionInit automatically enables auth
if [[ "$PROXY_ENABLE_SESSION_INIT" == "1" && "$PROXY_ENABLE_AUTH" != "1" ]]; then
  warn "PROXY_ENABLE_SESSION_INIT=1 requires auth; automatically enabling PROXY_ENABLE_AUTH"
  PROXY_ENABLE_AUTH=1
fi

bool() { [[ "$1" == "1" ]] && echo "true" || echo "false"; }

info "Generating proxy config → $CONFIG_FILE  (auth=$(bool $PROXY_ENABLE_AUTH) session-init=$(bool $PROXY_ENABLE_SESSION_INIT) tdai=$(bool $PROXY_ENABLE_TDAI))"
cat > "$CONFIG_FILE" <<YAML
# Auto-generated by start-proxy.sh - overwritten on every startup, please do not edit manually.
server:
  host: 0.0.0.0
  port: 8096
  forwardTimeoutMs: 600000

upstream:
  url: "${PROXY_UPSTREAM_URL}"
  apiKey: "${PROXY_UPSTREAM_API_KEY}"

log:
  file: ""
  level: info
  backend: console

# tdai core connection (used for injection / skill / auth retrieval)
tdai:
  enabled: $(bool $PROXY_ENABLE_TDAI)
  endpoint: "http://memory-core:8420"
  apiKey: "${MEMORY_CORE_GATEWAY_API_KEY}"
  serviceId: default
  memory:
    enabled: true
    inject: true
    writeL0: true
    recallL1: true
    injectL2L3: true

skill:
  endpoint: "http://memory-core:8420"
  serviceToken: "${MEMORY_CORE_GATEWAY_API_KEY}"

auth:
  enabled: $(bool $PROXY_ENABLE_AUTH)
  url: "http://memory-core:8420"
  timeoutMs: 5000

sessionInit:
  enabled: $(bool $PROXY_ENABLE_SESSION_INIT)
  maxRetries: 3
  injectAgentContext: true
  injectTaskContext: true
  headerAutoSelect:
    enabled: true
    teamHeader: "x-team-id"
    agentHeader: "x-agent-id"
    taskHeader: "x-task-id"
    onMismatch: "form"

costGuard:
  enabled: false

# Enable all three injectors: skill + knowledge + tdai-memory;
# knowledge relies on memory-hub to be up, otherwise internal hooks gracefully degrade to empty blocks.
injection:
  enabled: true
  injectors:
    - skill
    - knowledge
    - tdai-memory

redis:
  enabled: false
YAML

info "Starting proxy (image=$PROXY_IMAGE, port=$PROXY_PORT)"
$DOCKER run -d --name "$CONTAINER" \
  --network "$NETWORK" \
  --network-alias proxy \
  --add-host=host.docker.internal:host-gateway \
  -p "${PROXY_PORT}:8096" \
  -v "$CONFIG_FILE:/data/config.yaml:ro" \
  "$PROXY_IMAGE" >/dev/null

wait_healthy "$CONTAINER" 90
ok "proxy is running → http://localhost:${PROXY_PORT}/"
ok "  Usage: Point your coding agent's API base to http://localhost:${PROXY_PORT}"
