#!/usr/bin/env bash
# Start memory-core (core gateway, port 8420) independently, automatically run init-admin on first startup +
# persist the generated user_key to .admin-key for proxy / claude-code to use.
#
# Usage:
#   ./start-memory-core.sh
#
# Data is persisted to a named volume (default tdai-memory-core-data, can be changed via MEMORY_CORE_VOLUME in .env).
# Repeated executions will remove the old container and start a new one, keeping volume data — admin user_key is also preserved.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_lib.sh
source "$SCRIPT_DIR/_lib.sh"

load_env
require_vars MEMORY_CORE_IMAGE MEMORY_CORE_PORT MEMORY_CORE_VOLUME

# ── Gateway Internal Management Credentials ─────────────────────────────────────────
# Use ${VAR-default} (not :-default): allows explicitly setting it to an empty string in .env to disable Bearer gate.
#
# Currently, there is a **known incompatibility** between memory-core's Bearer gate and proxy auth: proxy calls
# /v3/meta/auth/verify without a Bearer token (source code omission, see MemoryProxy/src/auth.ts),
# so when proxy auth is enabled, MEMORY_CORE_GATEWAY_API_KEY must be left empty. It is empty by default.
MEMORY_CORE_GATEWAY_API_KEY="${MEMORY_CORE_GATEWAY_API_KEY-}"
MEMORY_CORE_ADMIN_USERNAME="${MEMORY_CORE_ADMIN_USERNAME:-admin}"

# admin user_key persistence location (host side; when volume data is cleared, this file must also be deleted)
ADMIN_KEY_FILE="${MEMORY_CORE_ADMIN_KEY_FILE:-$SCRIPT_DIR/.admin-key}"

if [[ -n "$MEMORY_CORE_GATEWAY_API_KEY" ]]; then
  warn "MEMORY_CORE_GATEWAY_API_KEY is not empty —— proxy's sessionInit/auth will currently fail due to missing Bearer."
  warn "For local testing, please leave MEMORY_CORE_GATEWAY_API_KEY empty in .env."
fi

CONTAINER=tdai-memory-core
NETWORK=tdai-memory-stack

# Create shared network (idempotent)
if ! $DOCKER network inspect "$NETWORK" >/dev/null 2>&1; then
  info "Create docker network $NETWORK"
  $DOCKER network create "$NETWORK" >/dev/null
fi

pull_image "$MEMORY_CORE_IMAGE"
rm_container_if_exists "$CONTAINER"

# ── Generate gateway config.yaml, mount to container /data/config/tdai-gateway.yaml ──
# The default image has no config, memory-core uses compile-time defaults (skill / knowledge modules disabled).
# Generate a minimal standalone+skill configuration from MEMORY_LLM_* in .env.
CORE_CONFIG_DIR="${MEMORY_CORE_CONFIG_DIR:-$SCRIPT_DIR/.memory-core-config}"
mkdir -p "$CORE_CONFIG_DIR"
CORE_CONFIG_FILE="$CORE_CONFIG_DIR/tdai-gateway.yaml"
info "Generate gateway config → $CORE_CONFIG_FILE"
cat > "$CORE_CONFIG_FILE" <<YAML
# Auto-generated by start-memory-core.sh —— Overwritten on every startup, please do not edit manually.
deployMode: standalone
stateBackend: local

server:
  port: 8420
  host: 0.0.0.0

data:
  baseDir: /data/tdai-memory

llm:
  baseUrl: "${MEMORY_LLM_BASE_URL:-}"
  apiKey: "${MEMORY_LLM_API_KEY:-}"
  model: "${MEMORY_LLM_MODEL:-}"
  maxTokens: 32000
  timeoutMs: 300000

memory:
  # promptMode: chat (default, general chat/teaching scenarios) | code (code engineering scenarios,
  # LLM will focus on extracting "what changed/what issues found/tool usage", normal chat might extract 0 items)
  # Override via MEMORY_PROMPT_MODE in .env.
  promptMode: ${MEMORY_PROMPT_MODE:-chat}
  capture: { enabled: true }
  extraction:
    enabled: true
    enableDedup: true
    maxMemoriesPerSession: 20
  persona:
    triggerEveryN: 50
    maxScenes: 15
  pipeline:
    everyNConversations: 5
    enableWarmup: true
    l1IdleTimeoutSeconds: 600
    l2DelayAfterL1Seconds: 90
    l2MinIntervalSeconds: 900
    l2MaxIntervalSeconds: 3600
  recall:
    enabled: true
    maxResults: 5
    scoreThreshold: 0.3
    strategy: hybrid
    timeoutMs: 5000
  storeBackend: sqlite
  embedding:
    provider: none

# ── Skill Module ──
skill:
  enabled: true
  routing:
    mode: bm25
    searchTopK: 20
  extraction:
    enabled: true
    maxIterations: 16
    queue:
      backend: local
      keyPrefix: tdai
      resultTtlSeconds: 86400
      lockTtlMs: 600000
      maxRetries: 2
      retryBackoffsMs: [5000, 15000]
  resources:
    maxResourceSizeBytes: 5000000
YAML

info "Start memory-core (image=$MEMORY_CORE_IMAGE, port=$MEMORY_CORE_PORT)"
$DOCKER run -d --name "$CONTAINER" \
  --network "$NETWORK" \
  --network-alias memory-core \
  -p "${MEMORY_CORE_PORT}:8420" \
  -v "${MEMORY_CORE_VOLUME}:/data/tdai-memory" \
  -v "$CORE_CONFIG_FILE:/data/config/tdai-gateway.yaml:ro" \
  -e TDAI_GATEWAY_PORT=8420 \
  -e TDAI_GATEWAY_HOST=0.0.0.0 \
  -e TDAI_GATEWAY_API_KEY="$MEMORY_CORE_GATEWAY_API_KEY" \
  -e TDAI_DATA_DIR=/data/tdai-memory \
  "$MEMORY_CORE_IMAGE" >/dev/null

wait_healthy "$CONTAINER" 90
ok "memory-core is up → http://localhost:${MEMORY_CORE_PORT}/"

# ── Admin user lifecycle ─────────────────────────────────────────
# First startup: pass our generated random user_key during init-admin, read it back from the response and save to file.
# Restart and already initialized (409): prioritize reading .admin-key; if the volume is new but .admin-key is
#   old, it cannot be recovered (volume/key must be in sync; prompt user to clean up).
#
# init-admin endpoint respects the provided user_key (see MemoryCore/src/metadata/store/sqlite-adapter.ts
# defaultKeyValue = input.default_key_value ?? generateUserKey()); as long as the volume is empty,
# and we provide a fixed key, we will get the key we specified. On first startup, the script generates a 32-byte random
# base32url —— each machine/each purge gets an independent key, avoiding collisions.

generate_user_key() {
  # sk-mem-<32 chars A-Za-z0-9>, consistent with metadata/utils/user-key.ts format
  # Use openssl (portable; tr filters +/= in base64 to 32 chars)
  local raw
  if command -v openssl >/dev/null 2>&1; then
    raw=$(openssl rand -base64 48 | LC_ALL=C tr -dc 'A-Za-z0-9' | head -c 32)
  else
    # Fallback: read enough urandom to ensure >=32 chars after filtering
    raw=$(head -c 256 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | head -c 32)
  fi
  echo "sk-mem-${raw}"
}

verify_user_key() {
  local key="$1"
  local code
  code=$(/usr/bin/curl -sS -o /dev/null -w "%{http_code}" --max-time 5 \
    -X POST -H "Content-Type: application/json" \
    -H "x-tdai-service-id: default" \
    ${MEMORY_CORE_GATEWAY_API_KEY:+-H "Authorization: Bearer ${MEMORY_CORE_GATEWAY_API_KEY}"} \
    "http://localhost:${MEMORY_CORE_PORT}/v3/meta/auth/verify" \
    -d "$(printf '{"user_key":"%s"}' "$key")" 2>/dev/null || echo "000")
  [[ "$code" == "200" ]]
}

info "Initialize admin user (username=${MEMORY_CORE_ADMIN_USERNAME}, key persistence → $ADMIN_KEY_FILE)..."

# Generate random key (for first init-admin; if file exists, reuse it)
if [[ -s "$ADMIN_KEY_FILE" ]]; then
  ADMIN_KEY=$(cat "$ADMIN_KEY_FILE")
  info "  Reuse saved admin key (.admin-key already exists)"
else
  ADMIN_KEY=$(generate_user_key)
fi

init_body=$(printf '{"username":"%s","user_key":"%s"}' \
  "$MEMORY_CORE_ADMIN_USERNAME" "$ADMIN_KEY")
init_resp=$(/usr/bin/curl -sS -o /tmp/init-admin.$$ -w "%{http_code}" \
  -X POST -H "Content-Type: application/json" \
  ${MEMORY_CORE_GATEWAY_API_KEY:+-H "Authorization: Bearer ${MEMORY_CORE_GATEWAY_API_KEY}"} \
  -H "x-tdai-service-id: default" \
  "http://localhost:${MEMORY_CORE_PORT}/v3/internal/meta/user/init-admin" \
  -d "$init_body" 2>/dev/null || echo "000")

case "$init_resp" in
  200)
    ok "admin user created"
    # Persist key (restrict permissions of the host file)
    umask 077
    echo -n "$ADMIN_KEY" > "$ADMIN_KEY_FILE"
    ok "  admin user_key saved to $ADMIN_KEY_FILE"
    ;;
  409)
    if [[ -s "$ADMIN_KEY_FILE" ]]; then
      ok "admin user already exists (skip init-admin, use key in $ADMIN_KEY_FILE)"
    else
      warn "admin user already exists, but $ADMIN_KEY_FILE is missing, unable to recover user_key."
      warn "Option A: Clean volume and rebuild —— ./stop-all.sh --purge && ./start-memory-core.sh"
      warn "Option B: Manually create new admin user_key (requires old key or gateway apiKey)"
    fi
    ;;
  *)
    warn "init-admin returned HTTP=${init_resp}, might need manual investigation:"
    cat /tmp/init-admin.$$ 2>/dev/null; echo
    ;;
esac
rm -f /tmp/init-admin.$$

# ── Validate admin key is usable ─────────────────────────────────────────
if [[ -s "$ADMIN_KEY_FILE" ]]; then
  ADMIN_KEY=$(cat "$ADMIN_KEY_FILE")
  if verify_user_key "$ADMIN_KEY"; then
    # Only do masked output at the end: full path masked, so the full value is not left in terminal history
    masked="${ADMIN_KEY:0:11}****${ADMIN_KEY: -4}"
    ok "admin user_key validation passed (auth/verify 200) —— $masked"
    ok "  key file: $ADMIN_KEY_FILE"
  else
    warn "admin user_key validation failed (auth/verify not 200). Check if $ADMIN_KEY_FILE matches the volume."
  fi
fi
