/**
 * VDB test residual database cleanup (**Destructive operation, requires explicit confirmation**).
 *
 * Background: The number of instance collections has reached the limit of 1500/1500, so it is not possible to create a new database for real device verification.
 * This script only reclaims the one-time collections generated by automated e2e testing to free up space for creating a new verification database.
 *
 * Security design (deletion operations, prefer to delete less rather than mistakenly delete):
 *   1. **Single prefix whitelist**: only delete libraries starting with `memory-tdai-test-`, hardcoded in
 *      ALLOWED_PREFIX, and not overridden by external parameters.
 *   2. **Blacklist secondary veto**: even if it matches the prefix, skip it if it falls within PROTECTED.
 *   3. **Default dry-run**: without `--confirm`, only print what will be deleted, without modifying data.
 *   4. Delete one by one + do not interrupt on failure, summarize at the end, for easier location.
 *
 Usage:
 *   node --import tsx scripts/cleanup-vdb-test-dbs.ts            # dry-run
 *   node --import tsx scripts/cleanup-vdb-test-dbs.ts --confirm   # actually delete
 */
import { TcvdbClient } from "../src/core/store/tcvdb-client.js";

const VDB_URL = process.env.VDB_URL;
const VDB_API_KEY = process.env.VDB_API_KEY;

if (!VDB_URL || !VDB_API_KEY) {
  console.error("Environment variables VDB_URL / VDB_API_KEY are required");
  process.exit(2);
}

/**
 * The only allowed library name prefix that can be deleted —— hardcoded, cannot be modified via parameters/environment variables.
 * These libraries are generated by automated e2e (names contain random run ids), and are for one-time use.
 */
const ALLOWED_PREFIX = "memory-tdai-test-";

/** Second veto list: do not delete even if hit. */
const PROTECTED: Array<(db: string) => boolean> = [
  (d) => d.startsWith("memory-tencentdb-testing"),
  (d) => d.startsWith("memory_dev_"),
  // The libraries currently used by .env.devcloud, must not be deleted
  (d) => d === (process.env.VDB_DATABASE ?? ""),
];

const CONFIRMED = process.argv.includes("--confirm");
const silent = { debug: () => {}, info: () => {}, warn: () => {}, error: () => {} };

function isDeletable(db: string): boolean {
  if (!db.startsWith(ALLOWED_PREFIX)) return false;
  return !PROTECTED.some((p) => p(db));
}

async function main() {
  const client = new TcvdbClient({
    url: VDB_URL!,
    username: process.env.VDB_USERNAME ?? "root",
    apiKey: VDB_API_KEY!,
    database: process.env.VDB_DATABASE ?? "default",
    timeout: 30_000,
    logger: silent,
  });

  const dbResp = await client.request<{ databases?: string[] }>("/database/list", {});
  const dbs = dbResp.databases ?? [];
  const targets = dbs.filter(isDeletable);

  console.log(`Total number of databases: ${dbs.length}`);
  console.log(`Matching "${ALLOWED_PREFIX}*" and not protected: ${targets.length} items`);

  if (targets.length === 0) {
    console.log("No libraries to clean, exiting.");
    return;
  }

  if (!CONFIRMED) {
    console.log("\n[DRY-RUN] The following libraries will be deleted (only execute for real with --confirm):");
    for (const db of targets.slice(0, 20)) console.log(`  ${db}`);
    if (targets.length > 20) console.log(`  ... and ${targets.length - 20} more`);
    console.log(`\nTotal of ${targets.length} libraries. No deletions were executed.`);
    return;
  }

  console.log(`\nStarting to delete ${targets.length} libraries...`);
  let ok = 0;
  const failed: Array<{ db: string; err: string }> = [];

  for (const [i, db] of targets.entries()) {
    // Verify once before deletion to prevent the list from being accidentally polluted
    if (!isDeletable(db)) {
      failed.push({ db, err: "failed safety re-check, skipped" });
      continue;
    }
    try {
      await client.dropDatabase(db);
      ok++;
      if ((i + 1) % 50 === 0) console.log(`   Progress ${i + 1}/${targets.length}`);
    } catch (err) {
      failed.push({ db, err: err instanceof Error ? err.message : String(err) });
    }
  }

  console.log(`\nCompleted: Success ${ok}, Failed ${failed.length}`);
  if (failed.length) {
    console.log("Failure details (first 10):");
    for (const f of failed.slice(0, 10)) console.log(`  ${f.db}: ${f.err}`);
  }
}

main().catch((err) => {
  console.error("cleanup failed:", err instanceof Error ? err.message : String(err));
  process.exitCode = 1;
});
