/**
 * Pending Task Action Store
 *
 * Stores the "pending confirmation" action drafts generated by the initial call of mem:create-task / mem:update-task.
 * They are fetched from here and written to the database when the user replies `... confirm` in the next turn; discarded on `... cancel` or timeout.
 *
 * Design trade-offs:
 *   - In-memory Map, lost on restart (user just resends, fits the "transient state" positioning).
 *   - TTL 5 minutes, lazy cleanup on getPending.
 *   - key = team_id:agent_id:session_id (aligns with the kernel side unique key semantics); if agent_id is missing,
 *     uses "-" as a placeholder to accommodate future paths without agent_id.
 */

export type PendingKind = "create" | "update";

export interface PendingCreateDraft {
  title: string;
  description: string;
  hint?: string;
}

export interface PendingUpdateDraft {
  /** Target task id (must be the "real task bound to the current session") */
  taskId: string;
  /** New description generated by LLM or passed directly by the user */
  description: string;
  /** Suggested status by LLM (e.g., "running" / "completed" / other free text), can be empty */
  statusSuggestion?: string;
  /** Current title of the original task (read-only for display) */
  currentTitle?: string;
  /** Current status of the original task (read-only for display) */
  currentStatus?: string;
  /** Input hint (args or "session context") */
  hint?: string;
}

export interface PendingCreatePayload {
  kind: "create";
  draft: PendingCreateDraft;
  /** The old task already bound to the current session, used to prompt "will replace binding" */
  currentTaskId: string;
  currentTaskTitle?: string;
}

export interface PendingUpdatePayload {
  kind: "update";
  draft: PendingUpdateDraft;
}

export type PendingPayload = PendingCreatePayload | PendingUpdatePayload;

interface PendingEntry {
  payload: PendingPayload;
  expiresAt: number;
}

const DEFAULT_TTL_MS = 5 * 60 * 1000;

const store = new Map<string, PendingEntry>();

export interface PendingKeyInput {
  team_id?: string;
  agent_id?: string;
  session_id?: string;
}

export function makePendingKey(input: PendingKeyInput): string {
  const t = input.team_id ?? "-";
  const a = input.agent_id ?? "-";
  const s = input.session_id ?? "-";
  return `${t}:${a}:${s}`;
}

export function setPending(key: string, payload: PendingPayload, ttlMs = DEFAULT_TTL_MS): void {
  store.set(key, { payload, expiresAt: Date.now() + ttlMs });
}

export function getPending(key: string): PendingPayload | null {
  const entry = store.get(key);
  if (!entry) return null;
  if (Date.now() >= entry.expiresAt) {
    store.delete(key);
    return null;
  }
  return entry.payload;
}

export function clearPending(key: string): boolean {
  return store.delete(key);
}

/** For testing: clear all */
export function _resetPendingStoreForTests(): void {
  store.clear();
}
