/**
 * api/users.ts — User + UserKey + UserConfig（meta/user/* + meta/user-key/* + meta/config/user/*）。
 */
import { metaPost, metaListAll, getCurrentUser, dedupeInFlight } from './base';
import type { PublicUser } from './types';

/** Kernel user/create response (CreateUserResult) — without username, with one-time key */
export interface CreateUserResult {
  user_id: string;
  user_type: 'normal' | 'system_admin';
  created_at: string;
  /** Default API key in plaintext, returned only in this response */
  default_user_key: string;
}

export const usersApi = {
  /** Paginate and list users; can pass in { username } for exact match or { user_ids } for filtering */
  list: (params?: { username?: string; user_ids?: string[] }) => metaListAll<PublicUser>('user/list', { ...params }),

  /** User Details */
  get: (userId: string) => metaPost<PublicUser>('user/get', { user_id: userId }),

  /**
   * Create new user (transparent proxy to backend user/create).
   *
   * Response is CreateUserResult: contains user_id / user_type / created_at / default_user_key.
   * default_user_key is a one-time plaintext key, returned only in this response.
   *
   * ⚠️ Permission: requires the current user to hold the system_admin permission; regular users → 403.
   */
  create: (data: { username: string; auth_provider: string; external_id: string; display_name?: string; email?: string }) =>
    metaPost<CreateUserResult>('user/create', data),

  /**
   * Create new user and explicitly specify user_key (transparently proxy to backend user/create-with-key).
   *
   * Sister interface of user/create: all behaviors align with create, the only difference is that default_user_key directly adopts the user_key provided by the caller,
   * rather than being automatically generated by the kernel. It is suitable for scenarios where "the panel admin needs to pre-allocate a known key to external distribution when creating an account."
   * If user_key conflicts, the kernel returns 409 `duplicate_user_key`, and the Panel backend passes it through as-is.
   *
   * ⚠️ Permission same as create: current user must hold system_admin permission; normal user → 403.
   */
  createWithKey: (data: { username: string; user_key: string }) =>
    metaPost<CreateUserResult>('user/create-with-key', data),

  /**
   * Delete user (transparent proxy to backend user/delete).
   *
   * ⚠️ Same permissions, must be called by system_admin.
   */
  delete: (userId: string) => metaPost<{ ok: boolean }>('user/delete', { user_id: userId }),
};

// ========================= User API Keys（meta/user-key/*）=========================
//
// Use standard meta action (same model as team/agent, dual Header authentication).

export interface UserKey {
  key_id: string;
  user_id?: string;
  name?: string;
  /** The displayable prefix of key (e.g., `sk-mem-ab12****`), returned by the kernel's list/get, used to identify which key it is without a password */
  key_prefix?: string;
  /** Plaintext key —— only appears once in the response, and afterwards (list/get) the kernel will not return it again, as a security design */
  key_value?: string;
  created_at?: string;
  expires_at?: string;
  revoked_at?: string;
  last_used_at?: string;
}

export const userKeysApi = {
  /** List all API Keys of the currently logged-in user (fetch the full list with paging by the kernel) */
  list: () => dedupeInFlight('user-key/list', () => metaListAll<UserKey>('user-key/list', {})),

  /** Create a new Key; the plaintext key_value in the return value is only displayed once, and the caller needs to display it to the user immediately */
  create: (data: { name?: string; expires_at?: string; user_id?: string }) => metaPost<UserKey>('user-key/create', data),

  /** Revoke a Key */
  revoke: (keyId: string) => metaPost<{ ok: boolean }>('user-key/revoke', { key_id: keyId }),
};

// ========================= User Config（meta/config/user/*）=========================

export type AssetCapabilityKey = 'skill.enabled' | 'llm_wiki.enabled' | 'code_graph.enabled' | 'chat_memory.enabled';

export interface UserConfigItem {
  module: string;
  param_name: AssetCapabilityKey | string;
  param_key: string;
  description: string;
  effective_value: string;
}

export interface UserConfigView {
  user_id: string;
  module: string;
  module_description: string;
  items: UserConfigItem[];
}

export type AssetCapabilityConfig = Record<AssetCapabilityKey, boolean>;

const ASSET_CAPABILITY_KEYS: AssetCapabilityKey[] = [
  'skill.enabled',
  'llm_wiki.enabled',
  'code_graph.enabled',
  'chat_memory.enabled',
];

function boolFromConfigValue(value: string | undefined): boolean {
  return value === undefined ? true : value === '1' || value.toLowerCase() === 'true';
}

export const userConfigApi = {
  get: (userId: string, module: string, paramName?: string) =>
    metaPost<UserConfigView>('config/user/get', { user_id: userId, module, param_name: paramName }),

  set: (userId: string, module: string, params: Record<string, string>) =>
    metaPost<{ ok: boolean }>('config/user/set', { user_id: userId, module, params }),

  getAssetCapabilities: async (): Promise<AssetCapabilityConfig> => {
    const me = await getCurrentUser();
    const view = await userConfigApi.get(me.user_id, 'asset_type');
    const byName = new Map(view.items.map((it) => [it.param_name, it.effective_value]));
    return Object.fromEntries(
      ASSET_CAPABILITY_KEYS.map((key) => [key, boolFromConfigValue(byName.get(key))]),
    ) as AssetCapabilityConfig;
  },

  setAssetCapability: async (key: AssetCapabilityKey, enabled: boolean) => {
    const me = await getCurrentUser();
    return userConfigApi.set(me.user_id, 'asset_type', { [key]: enabled ? '1' : '0' });
  },
};
