/**
 * Knowledge RPC ports — Wiki (15 endpoints) + Code-Graph (13 endpoints).
 *
 * Align docs/knowledge/knowledge-api.yaml (finalized 07/08/11). control
 * wiki/code-graph is not persistent; operations triggered by the UI are directly connected to the core through this port.
 *
 * Addressing rules (strictly consistent with yaml):
 *  - create / list / *write / *rm carries IdFields (team_id must be passed, user_id is optional);
 *  - get / ingest / delete / *ls / *read / graph / search and all code-graph
 *    The query endpoint is only addressed by the asset id (wiki_id/code_graph_id), no more
 *    team/agent/user/task ID (attribution is resolved by the kernel side via composite key).
 */

// ── Wiki ──

export interface WikiDetail {
  wiki_id: string;
  team_id: string;
  name: string;
  service_url: string | null;
  summary: string | null;
  status: 'draft' | 'pending' | 'processing' | 'ready' | 'failed';
  internal_status?: string | null;
  sync_error: string | null;
  version: string;
  owner_user_id: string | null;
  page_count: number | null;
  last_sync_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface WikiListResult {
  items: WikiDetail[];
  total: number;
}

export interface WikiIngestResult {
  wiki_id: string;
  status: string;
}

/** raw source file item (from `raw/sources/` filesystem stat). */
export interface RawFileEntry {
  filename: string;
  size: number;
  uploaded_at: string;
}

/** processed page items (from pages generated by ingest under `wiki/`). */
export interface PageEntry {
  id: string;
  title: string;
  type: string;
  path: string;
  locked?: boolean;
}

export interface WikiRawReadItem {
  filename: string;
  content?: string;
  not_found?: boolean;
}

export interface WikiRawWriteFile {
  filename: string;
  content: string;
}

export interface WikiRawWriteItem {
  filename: string;
  size: number;
}

export interface WikiRawRmResult {
  deleted_files: string[];
  deleted_pages: string[];
  rewritten_pages: number;
}

export interface WikiPageReadItem {
  ref: string;
  content?: string;
  not_found?: boolean;
}

export interface WikiPageWriteItem {
  ref: string;
  content: string;
}

export interface WikiPageWriteResultItem {
  ref: string;
  locked_injected?: boolean;
}

export interface WikiPageRmResult {
  deleted_pages: string[];
  rewritten_files: number;
}

export interface WikiGraphData {
  nodes: any[];
  edges: any[];
  communities?: any[];
}

export interface WikiSearchResult {
  results: Array<{ path: string; title: string; snippet: string; score: number; type: string }>;
  count: number;
}

export interface BatchDeleteResult {
  deleted_ids: string[];
  failed: Array<{ id: string; reason: string }>;
}

// ── Code-Graph ──

export interface CodeGraphDetail {
  code_graph_id: string;
  team_id: string;
  repo_name: string;
  repo_url: string;
  branch: string;
  commit_hash: string | null;
  service_url: string | null;
  summary: string | null;
  status: 'pending' | 'processing' | 'ready' | 'failed';
  sync_error: string | null;
  version: string;
  owner_user_id: string | null;
  stats: { files: number; nodes: number; edges: number } | null;
  last_sync_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface CodeGraphListResult {
  items: CodeGraphDetail[];
  total: number;
}

export interface CodeGraphSyncResult {
  code_graph_id: string;
  status: string;
}

export interface CodeGraphToolResult {
  text: string;
  isError: boolean;
}

// ── Port ──

export interface KnowledgeClientPort {
  //Wiki — Asset layer (create/list with IdFields; get/ingest/delete only asset id addressing)
  wikiCreate(teamId: string, name: string, userId?: string): Promise<WikiDetail>;
  wikiGet(wikiId: string): Promise<WikiDetail>;
  wikiIngest(wikiId: string): Promise<WikiIngestResult>;
  wikiDelete(wikiIds: string[]): Promise<BatchDeleteResult>;
  wikiList(teamId: string, opts?: { status?: string; limit?: number; offset?: number }): Promise<WikiListResult>;
  wikiUpdateMeta(wikiId: string, patch: { name?: string; summary?: string | null }): Promise<WikiDetail>;

  //Wiki — raw file layer (ls/read asset ids only; write/rm with IdFields)
  wikiRawLs(wikiId: string): Promise<{ items: RawFileEntry[] }>;
  wikiRawRead(wikiId: string, filenames: string[]): Promise<{ items: WikiRawReadItem[] }>;
  wikiRawWrite(teamId: string, wikiId: string, files: WikiRawWriteFile[], userId?: string): Promise<{ items: WikiRawWriteItem[] }>;
  wikiRawRm(teamId: string, wikiId: string, filenames: string[], userId?: string): Promise<WikiRawRmResult>;

  //Wiki — page file layer (ls/read asset ids only; write/rm with IdFields)
  wikiPageLs(wikiId: string): Promise<{ items: PageEntry[] }>;
  wikiPageRead(wikiId: string, refs: string[]): Promise<{ items: WikiPageReadItem[] }>;
  wikiPageWrite(teamId: string, wikiId: string, pages: WikiPageWriteItem[], userId?: string): Promise<{ items: WikiPageWriteResultItem[] }>;
  wikiPageRm(teamId: string, wikiId: string, refs: string[], userId?: string): Promise<WikiPageRmResult>;

  //Wiki — derived view (asset id addressing only)
  wikiGraph(wikiId: string): Promise<WikiGraphData>;
  wikiSearch(wikiId: string, query: string, limit?: number, graph?: { hop?: number; decay?: number; minScore?: number }): Promise<WikiSearchResult>;

  //Code-Graph (create/list with IdFields; get/sync/delete/query only asset id addressing)
  codeGraphCreate(teamId: string, repoUrl: string, branch?: string, userId?: string, repoName?: string): Promise<CodeGraphDetail>;
  codeGraphList(teamId: string, opts?: { status?: string; limit?: number; offset?: number }): Promise<CodeGraphListResult>;
  codeGraphGet(codeGraphId: string): Promise<CodeGraphDetail>;
  codeGraphSync(codeGraphId: string): Promise<CodeGraphSyncResult>;
  codeGraphDelete(codeGraphIds: string[]): Promise<BatchDeleteResult>;
  codeGraphUpdateMeta(codeGraphId: string, patch: { repo_name?: string; summary?: string | null }): Promise<CodeGraphDetail>;
  codeGraphQuery(codeGraphId: string, tool: string, params: Record<string, unknown>): Promise<CodeGraphToolResult>;
}
