/**
 * merge.ts — Page merging / deduplication (the "content merging" part of dedup, PRD FR-4).
 *
 * When a page generated in this run hits an existing page with the same slug:
 *   - Target page locked:true (manually edited by user via page/write) -> skip, never overwrite (§3.7-1 hard constraint).
 *   - Unlocked -> merge.
 *
 * Merging strategy (OQ-1 token optimization, tiered by old page size):
 *   1. Rule-based dedup: Candidate body is already covered by old page (duplicate ingest of same source) -> skip LLM, only update union of sources.
 *   2. Small page (old body <= threshold) -> full page rewrite (best quality, small old page, acceptable rewrite cost).
 *   3. Large page (old body > threshold) -> append mode: LLM outputs only "incremental fragment" appended to old page,
 *      preserving old page body as-is. Saves output tokens from regenerating full page and avoids losing old facts.
 *
 * After merging, recalculates frontmatter sources as the union of "old sources ∪ new sources",
 * ensuring raw/rm cascade cleanup works (§3.7-3).
 */

import type { LlmClient } from "./llm.js";
import { parseFrontmatter, buildPage } from "./frontmatter.js";

export type MergeDecision =
  | { action: "write"; content: string }   // New or rewrite
  | { action: "skip"; reason: string };     // locked, skip

export interface MergeOptions {
  /**
   * If old page body length exceeds this threshold, use "append mode" (saves output tokens);
   * otherwise use full page rewrite (quality first). Default is 4000.
   */
  fullRewriteMaxChars?: number;
}

/** Switch to append mode when old page body exceeds this length. */
export const DEFAULT_FULL_REWRITE_MAX_CHARS = 4000;

/** Merges two sources lists into a deduplicated union. */
export function unionSources(oldSources: string[], newSources: string[]): string[] {
  const set = new Set<string>();
  for (const s of [...oldSources, ...newSources]) {
    if (typeof s === "string" && s.trim()) set.add(s.trim());
  }
  return [...set];
}

/** Normalizes body for rule-based dedup: collapse whitespace, trim. */
function normalizeForCompare(body: string): string {
  return (body ?? "").replace(/\s+/g, " ").trim();
}

/**
 * Rule-based dedup: checks whether candidate body is completely covered by old page (no new information).
 * Conservative strategy — returns redundant only when normalized candidate body is non-empty and entirely a substring of old page body,
 * avoiding accidentally skipping real new information. Typical hit: same unedited source ingested repeatedly.
 */
export function isCandidateRedundant(oldBody: string, candidateBody: string): boolean {
  const cand = normalizeForCompare(candidateBody);
  if (!cand) return true; // Candidate has no body -> no new info
  const old = normalizeForCompare(oldBody);
  return old.includes(cand);
}

/**
 * Decides how a generated page should be committed to disk relative to an existing page.
 *
 * @param existingContent Disk content of existing page (null = does not exist, write directly)
 * @param candidateContent Candidate page content generated by LLM in this run
 * @param llm Client used for merging
 * @param options Merge behavior (thresholds, etc.)
 */
export async function mergePage(
  existingContent: string | null,
  candidateContent: string,
  llm: LlmClient,
  options: MergeOptions = {},
): Promise<MergeDecision> {
  // Target page does not exist -> write new page directly.
  if (existingContent == null) {
    return { action: "write", content: candidateContent };
  }

  // locked -> skip, protecting user manual edits.
  const oldParsed = parseFrontmatter(existingContent);
  if (oldParsed.frontmatter.locked === true) {
    return { action: "skip", reason: "Target page locked, skipping merge" };
  }

  const candParsed = parseFrontmatter(candidateContent);
  const union = unionSources(arr(oldParsed.frontmatter.sources), arr(candParsed.frontmatter.sources));

  // OQ-1 optimization 1: Rule-based dedup — candidate already covered by old page, skip LLM, update sources union only.
  if (isCandidateRedundant(oldParsed.body, candParsed.body)) {
    return {
      action: "write",
      content: buildPage({ ...oldParsed.frontmatter, sources: union }, oldParsed.body),
    };
  }

  const threshold = options.fullRewriteMaxChars ?? DEFAULT_FULL_REWRITE_MAX_CHARS;

  // OQ-1 optimization 2: Large page uses append mode, saving output tokens without losing old facts.
  if (oldParsed.body.length > threshold) {
    const merged = await appendMerge(oldParsed, candParsed.body, union, llm);
    return { action: "write", content: merged };
  }

  // Small page -> full page rewrite (quality first).
  const merged = await rewriteMerge(existingContent, candidateContent, llm);
  return { action: "write", content: merged };
}

const MERGE_SYSTEM = `You are a knowledge base maintainer. Merge two markdown pages on the same topic into one.
Merge principles:
- Preserve facts from the old page that still hold true — do not lose information.
- Incorporate new information from the new page.
- If old and new conflict, keep both and explicitly note the disagreement.
- Maintain YAML frontmatter format (type is required). Do NOT output a \`locked\` field.
- Preserve and merge [[wikilink]] cross-references in the body.
- Output the complete merged page directly (including frontmatter) — no extra commentary, no FILE blocks.`;

const APPEND_SYSTEM = `You are a knowledge base maintainer. Given an [existing page body] and [new material],
output only the incremental information that the existing page does NOT yet contain,
written as a concise markdown fragment (may include [[wikilink]]).
Requirements:
- Do not repeat content already in the existing page.
- Do not paraphrase or rewrite the entire page — only produce the "new" part.
- Do not output frontmatter, FILE blocks, or any explanation.
- If the new material adds nothing beyond what the existing page already covers, return an empty string.`;

/** Invokes LLM to perform full-page rewrite merge, enforcing sources to be old ∪ new union. */
async function rewriteMerge(
  existingContent: string,
  candidateContent: string,
  llm: LlmClient,
): Promise<string> {
  const prompt = `## Existing page (preserve its facts)
\`\`\`
${existingContent}
\`\`\`

## New page (merge its additions)
\`\`\`
${candidateContent}
\`\`\`

Output the merged complete page.`;

  const out = await llm.chat({ system: MERGE_SYSTEM, prompt, label: "merge-rewrite" });

  // Fallback: if LLM returns empty or missing frontmatter, fall back to candidate page to avoid losing pages.
  const mergedParsed = parseFrontmatter(out);
  if (!out.trim() || !mergedParsed.hasFrontmatter) {
    return reconcileSources(existingContent, candidateContent, candidateContent);
  }
  return reconcileSources(existingContent, candidateContent, out);
}

/**
 * Append-mode merge (saves tokens for large pages): requests LLM to output only incremental fragment, preserving old page body as-is and appending to the end.
 *
 * @param oldParsed   Old page parse result (frontmatter + body)
 * @param candidateBody Candidate page body
 * @param union       Pre-calculated sources union
 */
async function appendMerge(
  oldParsed: ReturnType<typeof parseFrontmatter>,
  candidateBody: string,
  union: string[],
  llm: LlmClient,
): Promise<string> {
  const prompt = `## Existing page body
${oldParsed.body}

## New material
${candidateBody}

Output only the incremental information not already in the existing page. If nothing is new, output an empty string.`;

  const fragment = (await llm.chat({ system: APPEND_SYSTEM, prompt, label: "merge-append" })).trim();

  // No additions -> update sources union only, body unchanged.
  if (!fragment) {
    return buildPage({ ...oldParsed.frontmatter, sources: union }, oldParsed.body);
  }

  const newBody = `${oldParsed.body.trimEnd()}\n\n${fragment}`;
  return buildPage({ ...oldParsed.frontmatter, sources: union }, newBody);
}

/** Rewrites merged result page's sources to the "old ∪ new" union. */
function reconcileSources(existingContent: string, candidateContent: string, mergedContent: string): string {
  const oldSrc = arr(parseFrontmatter(existingContent).frontmatter.sources);
  const newSrc = arr(parseFrontmatter(candidateContent).frontmatter.sources);
  const merged = parseFrontmatter(mergedContent);
  const union = unionSources(oldSrc, newSrc);
  return buildPage({ ...merged.frontmatter, sources: union }, merged.body);
}

function arr(v: unknown): string[] {
  return Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : [];
}
