/**
 * L3 Persona Generation Metric Reporter — L3 persona generation metric reporting.
 *
 * Non-intrusively reports the following metrics to Kafka after L3 persona generation is completed:
 *   - l3_generation_latency_ms : L3 persona generation end-to-end total latency (milliseconds)
 *   - persona_length_before    : Persona character count before update (0 on initial generation)
 *   - persona_length_after     : Persona character count after update
 *
 * Trace association notes:
 *   All metrics automatically inject the traceId of the current active span via metricProducer.send().
 *   L3 execution is in TracedTaskExecutor.executeL3() -> withSpan("core.l3.generation"),
 *   its child spans contain ai.generateText / gen_ai.chat spans automatically generated by Vercel AI SDK,
 *   carrying the gen_ai.request.model attribute. The traceId can be used to backtrack:
 *     - What model was used (gen_ai.request.model)
 *     - LLM prompt and response details
 *     - Full call chain of persona generation
 *     - Latency of this LLM invocation
 *
 * Design principles:
 *   1. After generation is completed, try-catch to report (fail silently)
 *   2. Regardless of report success or failure, generation results are unaffected
 *   3. Do not report when generation fails (hasError=true)
 *   4. Do not report when there is no instanceId
 */

import { metricProducer } from "./kafka-metric-producer.js";

// ============================
// Input Interface
// ============================

export interface L3LatencyMetricInput {
  /** Instance ID (Kafka key) */
  instanceId: string;
  /** L3 persona generation end-to-end total latency (milliseconds) */
  generationLatencyMs: number;
  /** Persona character count before update (pass 0 on initial generation) */
  personaLengthBefore: number;
  /** Persona character count after update */
  personaLengthAfter: number;
  /** Persona plain text before update (used to compute drift ratio, optional) */
  personaTextBefore?: string;
  /** Persona plain text after update (used to compute drift ratio, optional) */
  personaTextAfter?: string;
  /** Whether generation failed */
  hasError: boolean;
}

// ============================
// Reporter
// ============================

/**
 * Report L3 persona generation metrics to Kafka.
 *
 * Silently safe: any exceptions are try-catched and swallowed, never thrown outwards.
 */
export function reportL3LatencyMetrics(input: L3LatencyMetricInput): void {
  try {
    // Guard: Do not report on failure
    if (input.hasError) return;

    // Guard: Do not report without instanceId
    if (!input.instanceId) return;

    // 1. Report l3_generation_latency_ms
    try {
      metricProducer.send({
        metric: "l3_generation_latency_ms",
        instanceId: input.instanceId,
        value: Math.round(input.generationLatencyMs),
        source: "core",
      });
    } catch {
      // Fail silently
    }

    // 2. Report persona_length_before
    try {
      metricProducer.send({
        metric: "persona_length_before",
        instanceId: input.instanceId,
        value: input.personaLengthBefore,
        source: "core",
      });
    } catch {
      // Fail silently
    }

    // 3. Report persona_length_after
    try {
      metricProducer.send({
        metric: "persona_length_after",
        instanceId: input.instanceId,
        value: input.personaLengthAfter,
        source: "core",
      });
    } catch {
      // Fail silently
    }

    // 4. Report persona_drift_ratio (line-level diff)
    //    Calculation method: split old and new persona by lines, count added lines + deleted lines / total lines
    //    Value range [0, 1]: 0 = completely unchanged, 1 = completely rewritten
    //    Only calculated when before/after texts are present and it's not the first generation
    try {
      if (input.personaTextBefore != null && input.personaTextAfter != null && input.personaTextBefore.length > 0) {
        const driftRatio = computeLineDriftRatio(input.personaTextBefore, input.personaTextAfter);
        metricProducer.send({
          metric: "persona_drift_ratio",
          instanceId: input.instanceId,
          value: driftRatio,
          source: "core",
        });
      }
    } catch {
      // Fail silently
    }
  } catch {
    // Outermost catch — never throw outwards
  }
}

// ============================
// Helpers
// ============================

/**
 * Compute line-level drift ratio (Scheme C).
 *
 * Split old and new persona by lines (ignoring empty lines), calculate:
 *   drift = (added lines + deleted lines) / max(old lines + new lines, 1)
 *
 * Value range [0, 1]:
 *   0   = Content exactly the same
 *   ~0.1 = Minor tweaks (a few lines changed)
 *   ~0.5 = Significant modifications
 *   1   = Completely rewritten (not a single line matches)
 *
 * Performance: O(n) time + O(n) space, persona is usually 50-200 lines, takes < 0.1ms.
 */
export function computeLineDriftRatio(before: string, after: string): number {
  const oldLines = before.split("\n").filter((l) => l.trim().length > 0);
  const newLines = after.split("\n").filter((l) => l.trim().length > 0);

  const oldSet = new Set(oldLines);
  const newSet = new Set(newLines);

  const added = newLines.filter((l) => !oldSet.has(l)).length;
  const removed = oldLines.filter((l) => !newSet.has(l)).length;

  const total = oldLines.length + newLines.length;
  if (total === 0) return 0;

  // Normalize to [0, 1]
  return Math.min((added + removed) / total, 1);
}
