/**
 * L2 Scene Extraction Metric Reporter — L2 scene extraction metric reporting.
 *
 * Non-intrusively reports the following metrics to Kafka after L2 scene extraction is completed:
 *   - l2_extraction_latency_ms  : L2 scene extraction end-to-end total latency (milliseconds)
 *   - l2_llm_duration_ms       : L2 LLM invocation latency (milliseconds)
 *   - l2_scene_count_before    : Number of scenes before extraction
 *   - l2_scene_count_after     : Number of scenes after extraction
 *   - l2_scenes_created        : Number of scenes created this time
 *   - l2_scenes_updated        : Number of scenes updated this time
 *   - l2_scenes_deleted        : Number of scenes deleted this time
 *
 * Trace association notes:
 *   All metrics automatically inject the traceId of the current active span via metricProducer.send().
 *   L2 execution is in TracedTaskExecutor.executeL2() -> withSpan("core.l2.extraction"),
 *   its child spans contain ai.generateText / gen_ai.chat spans automatically generated by Vercel AI SDK,
 *   carrying the gen_ai.request.model attribute. The traceId can be used to backtrack:
 *     - What model was used
 *     - LLM request/response details
 *     - Latency of each link in the entire L2 extraction chain
 *
 * Design principles:
 *   1. After extraction is completed, try-catch to report (fail silently)
 *   2. Regardless of report success or failure, extraction results are unaffected
 *   3. Do not report when extraction fails (hasError=true)
 *   4. Do not report when there is no instanceId
 *   5. llmDurationMs being null means no LLM invocation timing, l2_llm_duration_ms is not reported
 */

import { metricProducer } from "./kafka-metric-producer.js";

// ============================
// Input Interface
// ============================

export interface L2LatencyMetricInput {
  /** Instance ID (Kafka key) */
  instanceId: string;
  /** L2 scene extraction end-to-end total latency (milliseconds) */
  extractionLatencyMs: number;
  /** LLM invocation latency (milliseconds). null means no LLM invocation timing */
  llmDurationMs: number | null;
  /** Number of scenes before extraction */
  sceneCountBefore: number;
  /** Number of scenes after extraction */
  sceneCountAfter: number;
  /** Number of scenes created this time */
  scenesCreated: number;
  /** Number of scenes updated this time */
  scenesUpdated: number;
  /** Number of scenes deleted this time */
  scenesDeleted: number;
  /** Whether extraction failed */
  hasError: boolean;
}

// ============================
// Reporter
// ============================

/**
 * Report L2 scene extraction metrics to Kafka.
 *
 * Silently safe: any exceptions are try-catched and swallowed, never thrown outwards.
 */
export function reportL2LatencyMetrics(input: L2LatencyMetricInput): void {
  try {
    // Guard: Do not report on failure
    if (input.hasError) return;

    // Guard: Do not report without instanceId
    if (!input.instanceId) return;

    // 1. Report l2_extraction_latency_ms
    try {
      metricProducer.send({
        metric: "l2_extraction_latency_ms",
        instanceId: input.instanceId,
        value: Math.round(input.extractionLatencyMs),
        source: "core",
      });
    } catch {
      // Fail silently
    }

    // 2. Report l2_llm_duration_ms (only when LLM timing is available)
    if (input.llmDurationMs !== null) {
      try {
        metricProducer.send({
          metric: "l2_llm_duration_ms",
          instanceId: input.instanceId,
          value: Math.round(input.llmDurationMs),
          source: "core",
        });
      } catch {
        // Fail silently
      }
    }

    // 3. Report l2_scene_count_before
    try {
      metricProducer.send({
        metric: "l2_scene_count_before",
        instanceId: input.instanceId,
        value: input.sceneCountBefore,
        source: "core",
      });
    } catch {
      // Fail silently
    }

    // 4. Report l2_scene_count_after
    try {
      metricProducer.send({
        metric: "l2_scene_count_after",
        instanceId: input.instanceId,
        value: input.sceneCountAfter,
        source: "core",
      });
    } catch {
      // Fail silently
    }

    // 5. Report l2_scenes_created
    try {
      metricProducer.send({
        metric: "l2_scenes_created",
        instanceId: input.instanceId,
        value: input.scenesCreated,
        source: "core",
      });
    } catch {
      // Fail silently
    }

    // 6. Report l2_scenes_updated
    try {
      metricProducer.send({
        metric: "l2_scenes_updated",
        instanceId: input.instanceId,
        value: input.scenesUpdated,
        source: "core",
      });
    } catch {
      // Fail silently
    }

    // 7. Report l2_scenes_deleted
    try {
      metricProducer.send({
        metric: "l2_scenes_deleted",
        instanceId: input.instanceId,
        value: input.scenesDeleted,
        source: "core",
      });
    } catch {
      // Fail silently
    }
  } catch {
    // Outermost catch — never throw outwards
  }
}
