import os

replacements = {
    r'C:\Users\yonik\TencentDB-Agent-Memory\MemoryCore\src\core\prompts\l1-extraction.ts': {
        '和 memory `content`。': 'and memory `content`.'
    },
    r'C:\Users\yonik\TencentDB-Agent-Memory\MemoryCore\src\core\instance-config-provider.ts': {
        '// LRU 重排 (H-3): 把 entry 移到 Map 末尾, 使 evict 时取首元素即为 LRU。': '// LRU Reorder (H-3): move entry to end of Map, so taking first element on evict is LRU.',
        '// delete+set 是 V8 上 Map 的 O(1) 操作。': '// delete+set is an O(1) operation for Map on V8.',
        '// 缓存未命中或已过期 → 进入 fetch 路径，先去重再请求 (H-2)': '// Cache miss or expired -> enter fetch path, deduplicate then request (H-2)',
        '// 清理 in-flight 标记。注意要在 await 之后清理 (即使 fetch 抛错也清),': '// Clean in-flight flag. Note to clean after await (even if fetch throws error),',
        '// 否则一次失败会让该 instanceId 永久卡住。': '// otherwise one failure will permanently stuck this instanceId.'
    },
    r'C:\Users\yonik\TencentDB-Agent-Memory\MemoryCore\src\core\persona\persona-generator.ts': {
        '自上次 Persona 更新后，以下': 'Since the last Persona update, the following',
        '个场景发生了变化。工程已为你预加载完整内容：': 'scenes have changed. The project has preloaded the full content for you:'
    },
    r'C:\Users\yonik\TencentDB-Agent-Memory\MemoryCore\src\core\prompts\l1-dedup.ts': {
        '统一候选记忆池': 'Unified Candidate Pool',
        '（空，没有已有记忆，所有新记忆直接 store）': '(Empty, no existing memories, all new memories store directly)',
        '条新记忆 (record_id:': 'New Memory (record_id:',
        '【关联候选 ID】': '[Related Candidate IDs]',
        '**输出语言**：`merged_content` 使用与候选池中已有记忆相同的语言。': '**Output Language**: `merged_content` uses the same language as existing memories in the candidate pool.',
        '第 ': 'No. '
    },
    r'C:\Users\yonik\TencentDB-Agent-Memory\MemoryCore\src\core\storage\buffer-storage.ts': {
        '/** _tasks.json 整体结构。 */': '/** _tasks.json overall structure. */',
        '/** `_tasks_dlq.json` 整体结构。 */': '/** `_tasks_dlq.json` overall structure. */'
    },
    r'C:\Users\yonik\TencentDB-Agent-Memory\MemoryCore\src\core\storage\sqlite.ts': {
        '"人工智能"': '"artificial intelligence"',
        '"人工 智能 人工智能"': '"artificial intelligence artificial intelligence"',
        '"用户五月去日本旅行"': '"user travels to Japan in May"',
        '"用户 五月 去 日本 旅行"': '"user May goes Japan travel"',
        '"人工智能的分支"': '"branch of artificial intelligence"',
        '"人工 智能 人工智能 的 分支"': '"artificial intelligence artificial intelligence \'s branch"'
    },
    r'C:\Users\yonik\TencentDB-Agent-Memory\MemoryCore\src\core\prompts\persona-generation.ts': {
        '输出语言': 'Output Language',
        '的所有自然语言内容使用与变化场景内容相同的语言；Markdown 语法、标签格式、文件名': 'all natural language content uses the same language as changed scenes; Markdown syntax, tag format, filename',
        '保持英文。': 'remain English.',
        '请你结合已有的': 'Please combine the existing',
        '和新增/变化的 L2 场景块，生成或更新一份高度精炼的团队工作原则文档。': 'and added/changed L2 scene blocks to generate or update a highly refined team operating doctrine.',
        '这份 L3 不是项目总结、进度记录、场景索引或事实汇总，而是团队在各种工作场合都可复用的 Operating Doctrine。它应帮助 Agent 在未来面对新任务时，知道应该如何判断、如何执行、如何避免错误。': 'This L3 is not a project summary, progress record, scene index, or fact compilation, but a team reusable Operating Doctrine. It helps the Agent know how to judge, execute, and avoid errors for future tasks.',
        '文件操作约束': 'File Operation Constraints',
        '必须使用文件工具将最终内容写入': 'Must use file tool to write final content to',
        '首次生成 / 大幅重写：使用': 'First generation / Major rewrite: use',
        '参数：': 'parameters: ',
        '完整内容。': 'full content.',
        '增量更新：使用': 'Incremental update: use',
        '旧内容片段': 'old content fragment',
        '新内容片段': 'new content fragment',
        '只能操作': 'Can only operate',
        '这一个文件，禁止读取或写入任何其他文件。': 'this one file, forbidden to read/write any other files.',
        '无需 read 工具': 'No read tool needed',
        '的完整内容已在用户消息中提供。': 'full content is provided in user message.',
        '写入内容必须只包含最终 Markdown 文档，不要包含分析过程或解释。': 'Written content must only contain final Markdown document, no analysis or explanation.',
        '严格禁止': 'Strictly Forbidden',
        '禁止超过 1200 字': 'Forbidden to exceed 1200 words',
        '最终': 'final',
        '必须高度压缩，求精不求多。': 'must be highly compressed, quality over quantity.',
        '禁止项目化碎片': 'Forbidden projectized fragments',
        '不要写只有在某个项目上下文里才懂的内容，例如"项目 v2 要优化"、"某模块继续推进"。': 'Do not write content only understood in a specific project context, e.g. "project v2 needs optimization".',
        '禁止流水账': 'Forbidden chronological accounts',
        '不要记录发生了什么、谁做了什么、某任务进展如何，除非它已经抽象成通用方法。': 'Do not record what happened or task progress, unless abstracted into a general method.',
        '禁止低层事实堆积': 'Forbidden accumulation of low-level facts',
        '项目名、版本号、任务名、PR、Issue、文档名通常不要进入 L3，除非它们代表可复用范式。': 'Project names, version numbers, task names, PRs, Issues usually should not enter L3 unless reusable paradigms.',
        '禁止语义不完整': 'Forbidden incomplete semantics',
        '每条原则必须脱离原项目也能理解，必须包含动作对象、适用条件或判断逻辑。': 'Each principle must be understandable out of original project, containing action object, condition, or logic.',
        '禁止个人画像化': 'Forbidden personal profiling',
        '不要生成成员性格、个人偏好、私人状态或情绪判断。': 'Do not generate member personality, personal preferences, private status, or emotional judgments.',
        '禁止过度推测': 'Forbidden over-speculation',
        '没有场景证据的信息不要臆测。': 'Do not speculate on information without scene evidence.',
        '核心目标': 'Core Objectives',
        '你要从 L2 场景中提炼所有工作场合都可复用的内容：': 'Extract from L2 scenes all content reusable in work contexts:',
        '以后类似任务应该按什么流程做。': 'How similar tasks should be processed in the future.',
        '团队长期遵守的工作原则。': 'Work principles team adheres to long-term.',
        '遇到取舍时按什么标准判断。': 'Criteria for trade-offs.',
        '哪些事情不能做，哪些内容不能自动化。': 'What cannot be done, what cannot be automated.',
        '哪些做法会导致错误、污染记忆、降低质量。': 'Practices causing errors, memory pollution, quality drops.',
        '执行任务、更新记忆、生成结果时应遵守什么规则。': 'Rules for executing tasks, updating memory, generating results.',
        '项目事实、任务状态、资产名称只作为证据来源，不应直接进入 L3。只有当它们能抽象成跨场景规则时，才写入。': 'Project facts, task status, asset names only serve as evidence. Only write if abstractable to cross-scene rules.',
        '过滤标准': 'Filtering Criteria',
        '写入 L3 前逐条检查：': 'Check one by one before writing to L3:',
        '通用性': 'Generality',
        '这条内容是否适用于多个项目、多个任务或多种工作场合？': 'Does this apply to multiple projects, tasks, or work contexts?',
        '完整性': 'Completeness',
        '脱离原始项目后，读者是否仍能理解它在要求什么？': 'Without original project context, can the reader still understand its requirement?',
        '可执行性': 'Actionability',
        '是否能据此改变未来行为？': 'Can Agent change future behavior based on this?',
        '稳定性': 'Stability',
        '它是否可能长期有效，而不是一次性任务状态？': 'Is it likely long-term effective, not a one-off task status?',
        '精炼性': 'Conciseness',
        '能否用更少字表达？是否可以合并进已有原则？': 'Can it be expressed with fewer words? Can it be merged into existing principles?',
        '如果任一答案是否定，优先不写入。': 'If any answer is no, prioritize not writing.',
        '增量更新策略': 'Incremental Update Strategy',
        '面对变化场景，自主判断：': 'Facing changed scenes, autonomously judge:',
        '强化': 'Reinforce',
        '新场景只是佐证已有原则，压缩进原句或不改。': 'New scene only corroborates existing principle, compress into original sentence or do not change.',
        '补充': 'Supplement',
        '出现新的通用 SOP、禁忌、判断逻辑或 Agent 规则。': 'New general SOP, taboo, decision logic or Agent rule appears.',
        '修正': 'Correct',
        '旧原则被新证据推翻或边界变清晰。': 'Old principle overturned by new evidence or boundaries become clearer.',
        '重构': 'Refactor',
        '文档变散、变长、变项目化时，整体压缩重写。': 'When document becomes scattered, long, projectized, compress and rewrite overall.',
        '不改': 'No change',
        '新增内容只有项目状态、普通任务或低层事实时，不更新 L3。': 'When new content only has project status, general tasks, or low-level facts, do not update L3.',
        '不要把每次变化追加为新条目。L3 应持续压缩，保持少而准。': 'Do not append each change as a new entry. L3 should be continuously compressed, sparse and accurate.',
        '输出模板': 'Output Template',
        '请参考以下格式，使用': 'Please refer to the following format, use',
        '或': 'or',
        '工具写入最终内容。可以删减章节，但必须保持 Markdown 格式，全文不超过 1200 字。': 'tool to write final content. Chapters can be deleted, but keep Markdown format, total text < 1200 words.',
        '一句话概括团队最核心、最通用的工作方法或 Agent 执行原则。': 'One sentence summarizing team\'s core, most general work method or Agent execution principle.',
        '只写跨工作场景稳定成立的高层原则。每条必须语义完整。': 'Only write high-level principles stably valid across work scenes. Each must be semantically complete.',
        '原则': 'Principle',
        '适用条件 / 判断逻辑 / 为什么重要': 'Applicable conditions / Decision logic / Why important',
        '只写能被反复执行的流程。不要写具体项目步骤。': 'Only write repeatable processes. Do not write specific project steps.',
        '名称': 'Name',
        '当': 'When',
        '触发条件': 'Trigger condition',
        '时，先': ', first',
        '步骤1': 'Step 1',
        '，再': ', then',
        '步骤2': 'Step 2',
        '，最后': ', finally',
        '产出/验收标准': 'Deliverable/Acceptance criteria',
        '记录取舍标准和优先级。': 'Record trade-off criteria and priority.',
        '场景': 'Scene',
        '时，优先': ', prioritize',
        '而不是': 'instead of',
        '，因为': ', because',
        '原因': 'Reason',
        '记录禁忌、边界和错误模式。': 'Record taboos, boundaries, and error patterns.',
        '错误做法': 'Error practice',
        '；应改为': '; instead use',
        '推荐做法': 'Recommended practice',
        '记录 Agent 在工作中默认遵守的行为规则。': 'Record behavioral rules Agent defaults to follow at work.',
        '应': 'should',
        '行为规则': 'Behavioral rule',
        '，避免': ', avoiding',
        '风险': 'Risk',
        '最后更新': 'Last Updated',
        '当前时间': 'Current Time',
        '来源场景': 'Source Scenes',
        '场景数': 'Scene Count',
        '个': '',
        '记忆总数': 'Total Memories',
        '总记忆数': 'Total Memory Count',
        '条': '',
        '成功标准': 'Success Criteria',
        '必须使用 write 或 edit 写入': 'Must use write or edit to write to',
        '最终内容不超过 1200 字': 'Final content does not exceed 1200 words',
        '只保留所有工作场合可复用的原则、SOP、禁忌、判断逻辑和 Agent 规则': 'Only retain principles, SOPs, taboos, decision logics, Agent rules reusable in all work contexts',
        '每条内容脱离具体项目后仍语义完整': 'Each content is semantically complete out of specific project',
        '求精不求多，能不写就不写，能合并就合并': 'Quality over quantity, omit if possible, merge if possible',
        '不写项目进度、任务流水账、版本碎片或场景索引': 'Do not write project progress, task chronological accounts, version fragments, or scene indices',
        '不要添加场景导航（工程会自动追加 Scene Navigation 和场景索引）': 'Do not add scene navigation (Engineering automatically appends Scene Navigation and scene indices)',
        '只操作': 'Only operate on'
    }
}

for path, rep in replacements.items():
    if not os.path.exists(path):
        continue
    with open(path, 'r', encoding='utf-8') as f:
        c = f.read()
    for k, v in rep.items():
        c = c.replace(k, v)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(c)

print('Translated final remaining bits.')
