/**
 * SkillTriggerService — Archiving phase (§7.4).
 *
 * The Handler calls this module after determining that "archiving is needed" in the main flow.
 * It completes "**archive first, then register task**" in the following order:
 *   ① Generate archive_key / task_id / archived_at_ms
 *   ② Write archive file (treat existing as success; if this is slow or fails, no orphan task is left behind)
 *   ③ Acquire tasks-mutex → read `_tasks.json` → append task → write back → enqueue in Redis within the same critical section
 *
 * Sequence modification history:
 *   2026-07-20 — Original order was ①→②(write _tasks.json + enqueue within tasksMutex)→③(write archive),
 *   which triggered in the test environment: writeArchive was slower than worker BRPOP (due to COS self-signed TLS +
 *   internal DNS jitter causing single puts to take ~10s). The worker aggressively readArchive, got null, judged it as a ghost,
 *   and silently dropped real tasks. After changing to "archive first, then task": archive slowness/failures
 *   report an error in-place on the handler side. The worker never sees a task without an archive, and there is no ghost
 *   misjudgment under happy-path conditions.
 *
 * Failure states under the new order:
 *   - writeArchive throws error → handler gets the exception, no residue in _tasks.json, no agent in Redis;
 *     Client retries and runs the full process again (archive is idempotent: same archived_at_ms skips without overwriting).
 *   - writeArchive succeeds → writeTasks / enqueueAgent inside the mutex fails → leaves only an
 *     "orphan archive" (a 4-to-tens-of-KB jsonl file, unseen by the worker, cleaned up by COS lifecycle
 *     or future GC). This is far better than the previous state: no more risk of dropping tasks.
 */

import { randomUUID } from "node:crypto";

import type {
  AgentTuple,
  ISkillAgentTaskQueue,
} from "./agent-task-queue.js";
import type {
  BufferedMessages,
  SessionKey,
  SkillBufferStorage,
  SkillTaskEntry,
} from "./buffer-storage.js";
import { obsLogger } from "../../report/obs-logger.js";

export interface TriggerArchiveInput {
  session: SessionKey;
  bufferAtTrigger: BufferedMessages;
  /** Business-side task reference (pass-through field), optional. */
  taskRefId?: string;
  /**
   * Exclusive to direct-trigger (`/v3/skill/extract`): main Agent extraction prompt,
   * saved to SkillTaskEntry.reason, and passed through to extractor.extract upon Worker consumption.
   * Not passed on the conversation/add path.
   */
  reason?: string;
  /**
   * Exclusive to direct-trigger: extractor LLM iteration limit, saved to SkillTaskEntry.max_iterations.
   * Not passed on the conversation/add path (uses extractor-side defaults).
   */
  maxIterations?: number;
  /**
   * The request_id generated by the upstream handler. When provided, the internal phase obsLogger events
   * inside the trigger will include it, making it easy to filter the entire handler + trigger + worker chain by req_id.
   * Omitting it does not affect functionality.
   */
  perfRequestId?: string;
}

export interface TriggerArchiveResult {
  taskId: string;
  archivedAtMs: number;
  archiveKey: string;
}

export interface SkillTriggerServiceOptions {
  buffer: SkillBufferStorage;
  queue: ISkillAgentTaskQueue;
  /**
   * tasks-mutex lock TTL, default 10000ms. **The lock's own expiration time** — just a fallback
   * to automatically release it if the lock-holding process crashes. The actual critical section should be much shorter than this value (COS read-modify-write is usually <300ms).
   */
  tasksMutexLockTtlMs?: number;
  /**
   * Maximum wait time to contend for tasks-mutex, default 30000ms (30s).
   * Queueing time accumulates when high-concurrency archiving happens for the same agent (multiple sessions entering the critical section simultaneously).
   * waitDeadline must be >> single critical section duration × expected queue depth.
   */
  tasksMutexWaitDeadlineMs?: number;
  /** Time source, used for test injection. */
  now?: () => number;
}

export class SkillTriggerService {
  private readonly buffer: SkillBufferStorage;
  private readonly queue: ISkillAgentTaskQueue;
  private readonly tasksMutexLockTtlMs: number;
  private readonly tasksMutexWaitDeadlineMs: number;
  private readonly now: () => number;

  constructor(opts: SkillTriggerServiceOptions) {
    this.buffer = opts.buffer;
    this.queue = opts.queue;
    this.tasksMutexLockTtlMs = opts.tasksMutexLockTtlMs ?? 10_000;
    this.tasksMutexWaitDeadlineMs = opts.tasksMutexWaitDeadlineMs ?? 30_000;
    this.now = opts.now ?? (() => Date.now());
  }

  /**
   * Triggers an archive. Executes §7.4 ①→②→③→④.
   * Failures throw exceptions, letting the Handler convert to 500 and hand it to the Client for retry.
   */
  async archive(input: TriggerArchiveInput): Promise<TriggerArchiveResult> {
    const { session, bufferAtTrigger, taskRefId } = input;

    // ① Generate identifiers
    const archivedAtMs = this.now();
    const archiveKey = this.buffer.archiveKey(session, archivedAtMs);
    // The prefix `skill-extract-task-` is an internal anchor (clearly distinguished from business-side task_id).
    // One archive = one SkillTaskEntry.task_id; the handler-side `[skill-perf] phase=trigger.enqueueAgent
    // task_id=…` and the worker-side `[skill-perf] kind=worker phase=consume.*` share this same
    // value, allowing a single grep to pull the full handler + worker dual-segment latency. Legacy data prefix `task-` will be
    // naturally consumed by the worker, no migration risk (filtering compares task_id values equally, without parsing prefixes).
    const taskId = `skill-extract-task-${randomUUID().slice(0, 8)}`;
    const agent: AgentTuple = {
      // 2026-07-30 instance_id shoved into tuple; worker pool routes to the
      // corresponding instance resources using this after dequeuing. If not provided or empty, it directly throws.
      instance_id: session.instance_id,
      space_id: session.space_id,
      user_id: session.user_id,
      team_id: session.team_id,
      agent_id: session.agent_id,
    };

    const entry: SkillTaskEntry = {
      task_id: taskId,
      session_id: session.session_id,
      user_id: session.user_id,
      team_id: session.team_id,
      agent_id: session.agent_id,
      space_id: session.space_id,
      task_ref_id: taskRefId,
      archive_key: archiveKey,
      archived_at_ms: archivedAtMs,
      enqueued_at_ms: archivedAtMs,
      reason: input.reason,
      max_iterations: input.maxIterations,
    };

    // [obs] Five critical IOs in the archive segment: writeArchive / mutex acquire / readTasks /
    // writeTasks / enqueueAgent. In past incidents, it was writeArchive taking 10s that crashed
    // the worker-side null-check logic; here we structure events step by step, relating fields by req_id / task_id.
    // obsLogger has internal try/catch + backend fallback, so no extra defense is needed.
    const rid = input.perfRequestId;
    const instanceId = session.instance_id;

    // ② Write archive first (treat existing as success)
    //
    // The rationale for the order here: the worker-side readArchive getting null will judge it as a ghost and directly delete
    // the corresponding task; if the archive segment is later than the task segment, any COS jitter (self-signed TLS slow handshake,
    // internal DNS re-resolution, etc.) will prop open a "task registered but archive not yet written" window.
    // If worker BRPOP beats this window, it will drop the real task as a ghost (2026-07-20 production
    // site: writeArchive took 10s, two cores splitting work, and the other core dropped the task at 5s).
    // After changing to archive first, then task: writeArchive throwing errors/slowness will not
    // create orphan tasks; the worker will always only see the task when the archive already exists.
    //
    // Failure state: writeArchive throws error → throws exception directly back to handler, no residue.
    const t0Arch = Date.now();
    await this.buffer.writeArchive(session, archivedAtMs, bufferAtTrigger);
    obsLogger.info("skill.trigger.write_archive", {
      req_id: rid, task_id: taskId, instance_id: instanceId,
      dur_ms: Date.now() - t0Arch,
      archive_key: archiveKey,
    });

    // ③ Acquire mutex → CAS append task to tail → enqueue within the same lock
    //
    // Critical guarantee (root cause of ghost tasks): writeTasks and enqueueAgent must complete within the same
    // tasks-mutex critical section, otherwise a race window occurs between the Worker's "null-check → removeAgent":
    // Before the Worker calls removeAgent outside the mutex, this function's
    // enqueueAgent might have skipped LPUSH because the old agent was still in the Set (SADD returns 0),
    // resulting in the new task landing in _tasks.json, but the Redis queue having zero record
    // for this agent — the task is permanently stuck, and no subsequent mechanism will re-trigger it.
    // Folding enqueueAgent into the same lock, in tandem with the Worker-side fix (see extract-worker.ts),
    // ensures "write task + enqueue" and "null-check + dequeue" are mutually exclusive and will not cross.
    const t0MutexEntry = Date.now();
    await this.queue.withTasksMutex(
      agent,
      { lockTtlMs: this.tasksMutexLockTtlMs, waitDeadlineMs: this.tasksMutexWaitDeadlineMs },
      async () => {
        const mutexAcquiredAt = Date.now();
        obsLogger.info("skill.trigger.mutex_acquire", {
          req_id: rid, task_id: taskId, instance_id: instanceId,
          dur_ms: mutexAcquiredAt - t0MutexEntry,
        });

        const t0Read = Date.now();
        const doc = await this.buffer.readTasks(agent);
        obsLogger.info("skill.trigger.read_tasks", {
          req_id: rid, task_id: taskId, instance_id: instanceId,
          dur_ms: Date.now() - t0Read,
          existing_tasks: doc.tasks.length,
        });

        doc.tasks.push(entry);
        doc.updated_at_ms = archivedAtMs;

        const t0Write = Date.now();
        await this.buffer.writeTasks(agent, doc);
        obsLogger.info("skill.trigger.write_tasks", {
          req_id: rid, task_id: taskId, instance_id: instanceId,
          dur_ms: Date.now() - t0Write,
          total_tasks: doc.tasks.length,
        });

        const t0Enq = Date.now();
        const enqueued = await this.queue.enqueueAgent(agent);
        obsLogger.info("skill.trigger.enqueue_agent", {
          req_id: rid, task_id: taskId, instance_id: instanceId,
          dur_ms: Date.now() - t0Enq,
          added: enqueued,
        });
      },
    );
    obsLogger.info("skill.trigger.mutex_total", {
      req_id: rid, task_id: taskId, instance_id: instanceId,
      dur_ms: Date.now() - t0MutexEntry,
    });

    return { taskId, archivedAtMs, archiveKey };
  }
}
